### ISSUE TITLE
[Bug] Unexpected behavior or crash when removing labels

### ISSUE THREAD

**Issue by PunningLinguist** [olivierkes/manuskript#1010]
If you remove a label from the settings window, all labels lower than it in the list will be changed by one position. For example, if the list of labels is [Idea, Note, Chapter, Scene], and you delete Idea, everything formerly labeled Chapter will be labeled Scene, everything labeled Note will get labeled Chapter, etc.

If you have anything labeled with the last label in the list, the program will crash upon doing anything after closing the settings window. The output is different depending on what you do to trigger the crash after closing the settings window. In my testing I've found three different variations of this, listed below. (In all cases the initial critical error is the same but the rest of the output is different.)

In most cases, Manuskript will crash with the following output:

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 25, in paint
    colors = outlineItemColors(item)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 221, in outlineItemColors
    col = iconColor(mw.mdlLabels.item(toInt(lbl)).icon())
AttributeError: 'NoneType' object has no attribute 'icon'
WARNING> QPaintDevice: Cannot destroy paint device that is being painted
```

If you are already in the outline view and you try to select an item that is labeled with the last label in the list, the same critical error will appear but it will be followed by a segmentation fault:

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 25, in paint
    colors = outlineItemColors(item)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 221, in outlineItemColors
    col = iconColor(mw.mdlLabels.item(toInt(lbl)).icon())
AttributeError: 'NoneType' object has no attribute 'icon'
Fatal Python error: Segmentation fault

Current thread 0x00007f8afc544740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 243 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 309 in run
  File "/usr/bin/manuskript", line 30 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtDBus, PyQt5.QtDesigner, PyQt5.QtHelp, PyQt5.QtMultimedia, PyQt5.QtMultimediaWidgets, PyQt5.QtOpenGL, PyQt5.QtPositioning, PyQt5.QtLocation, PyQt5.QtPrintSupport, PyQt5.QtQuick, PyQt5.QtQuickWidgets, PyQt5.QtSql, PyQt5.QtSvg, PyQt5.QtTest, PyQt5.QtWebChannel, PyQt5.QtX11Extras, PyQt5.QtXml, PyQt5.QtXmlPatterns, lxml._elementpath, lxml.etree (total: 25)
Segmentation fault (core dumped)
```

If you're editing the text of an item that is labeled with the last label in the list and you click within the text editor, you get this output instead:

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/treeDelegates.py", line 30, in paint
    colors = outlineItemColors(item)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 221, in outlineItemColors
    col = iconColor(mw.mdlLabels.item(toInt(lbl)).icon())
AttributeError: 'NoneType' object has no attribute 'icon'
WARNING> Exception ignored in atexit callback: <function shutdown at 0x7fdabb415090>
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 720, in focusOutEvent
    self.submit()
  File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 330, in submit
    self.updateTimer.stop()
RuntimeError: wrapped C/C++ object of type QTimer has been deleted

The above exception was the direct cause of the following exception:

SystemError: _PyEval_EvalFrameDefault returned a result with an exception set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtGui.QHideEvent'> returned a result with an exception set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.QtMsgType'> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 2174, in shutdown
    for wr in reversed(handlerList[:]):
SystemError: <built-in method __reversed__ of list object at 0x7fda8a5e3980> returned a result with an exception set
```

And lastly, although I've only ever had it happen once while testing and was not able to reproduce it, if the project is somehow saved before the crash, reopening the project will cause Manuskript to crash with the first output.

Tested on Arch Linux on the version of Manuskript available in the software repository (0.13.1) as well as the current develop branch.

**Comment by DarrenCook** [comment]
I just hit this exact bug; on latest develop branch.

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/path/to/manuskript/bin/ui/views/treeDelegates.py", line 30, in paint
    colors = outlineItemColors(item)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/manuskript/bin/functions/__init__.py", line 230, in outlineItemColors
    col = iconColor(mw.mdlLabels.item(toInt(lbl)).icon())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'icon'
```

I added a custom label, from with  Assigned it to a couple of chapters.
Then a few minutes I unassigned it from both, and then removed it from the labels list.
The app then crashed, and immediately dies with the above message every time I try to restart it.

I've been comparing to an older backup (I clone my book directory every 10 minutes now) and labels.txt was identical to how it was before.
Finally I saw that my change to the chapter's folder.txt had never saved before editing the list of labels had crashed it!
So `label:          6` was still in there.

**Comment by DarrenCook** [comment]
Here is one way to fix it:
```
diff --git manuskript/functions/__init__.py manuskript/functions/__init__.py
index e168506..4d6422d 100644
--- manuskript/functions/__init__.py
+++ manuskript/functions/__init__.py
@@ -224,10 +224,11 @@ def outlineItemColors(item):
 
     # Label
     lbl = item.data(Outline.label)
-    if lbl == "":
-        col = QColor(Qt.transparent)
-    else:
-        col = iconColor(mw.mdlLabels.item(toInt(lbl)).icon())
+    col = QColor(Qt.transparent)
+    if lbl != "":
+        icon = mw.mdlLabels.item(toInt(lbl))
+        if icon:
+            col = iconColor(icon.icon())
     # if col == Qt.black:
     #     # Don't know why, but transparent is rendered as black
     #     col = QColor(Qt.transparent)
```

**Comment by DarrenCook** [comment]
An unknown label also completely breaks search.
```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/path/to/manuskript/manuskript/ui/search.py", line 142, in search
    results += model.searchOccurrences(searchRegex, filteredColumns)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/manuskript/manuskript/models/searchableModel.py", line 11, in searchOccurrences
    results += item.searchOccurrences(searchRegex, column)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/manuskript/manuskript/models/searchableItem.py", line 16, in searchOccurrences
    return [self.wrapSearchOccurrence(column, startPos, endPos, context) for (startPos, endPos, context) in search(searchRegex, self.searchData(column))]
                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/manuskript/manuskript/models/outlineItem.py", line 558, in searchData
    searchData = mainWindow.mdlLabels.item(F.toInt(self.label()), 0).text()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

The places to fix to make the code more resilient could be never-ending! Hunting for places where function calls are embedded as arguments like that would be a good start. Quite a big job, though.
