### ISSUE TITLE
Error while loading version of the msk format

### ISSUE THREAD

**Issue by ankiedos** [olivierkes/manuskript#1030]
I don't know Python very well, so I can't help much, but when I was trying to open a project, an exception concerning version loading has occured:
```
Logging to STDERR.
Logging to file: C:/Users/***/AppData/Local/manuskript/manuskript\logs\2022-04-16_14-37-24_manuskript#12532.log
Operating System: Windows 10
Hardware: AMD64
Running in a frozen (packaged) state.
* sys.frozen = True
* sys._MEIPASS = C:\Users\***\Downloads\manuskript-0.12.0-fix-7e05b72-win32\manuskript
* sys.executable = ('C:\\Users\\*** '
 '***\\Downloads\\manuskript-0.12.0-fix-7e05b72-win32\\manuskript\\manuskript.exe')
* sys.argv = ['manuskript.exe']
* sys.path = ['C:\\Users\\*** '
 '***\\Downloads\\manuskript-0.12.0-fix-7e05b72-win32\\manuskript\\base_library.zip',
 'C:\\Users\\*** '
 '***\\Downloads\\manuskript-0.12.0-fix-7e05b72-win32\\manuskript\\..',
 'C:\\Users\\*** '
 '***\\Downloads\\manuskript-0.12.0-fix-7e05b72-win32\\manuskript\\lib-dynload',
 'C:\\Users\\*** '
 '***\\Downloads\\manuskript-0.12.0-fix-7e05b72-win32\\manuskript']
* sys.prefix = ('C:\\Users\\*** '
 '***\\Downloads\\manuskript-0.12.0-fix-7e05b72-win32\\manuskript')
Manuskript 0.12.0 (Python 3.8.9)
* PyQt 5.15.4 (compiled against Qt 5.15.2)
  * Qt 5.15.2 (runtime)
* lxml.etree 4.6.3.0
  * libxml   2.9.5 (compiled: 2.9.5)
  * libxslt  1.1.30 (compiled: 1.1.30)
* pyEnchant 3.2.0 (libenchant: 2.2.7)
* pySpellChecker 0.6.2
* Symspellpy 6.7.0
* Markdown 3.3.4
Web rendering engine: QTextEdit
Preferred translation: ['pl-PL', 'en-US'] (based on available ui languages)
Loaded translation: manuskript_pl_PL.qm
Last accessed directory "C:/Users/***/Desktop" loaded.
An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 165, in openFile
  File "manuskript\mainWindow.py", line 605, in loadProject
  File "manuskript\mainWindow.py", line 891, in loadDatas
  File "manuskript\loadSave.py", line 60, in loadProject
ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 165, in openFile
  File "manuskript\mainWindow.py", line 605, in loadProject
  File "manuskript\mainWindow.py", line 891, in loadDatas
  File "manuskript\loadSave.py", line 60, in loadProject
ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
```
And when I opened the file in Notepad, I found out that it is filled with zeros (but numeric, not characters).

**Comment by TheJackiMonster** [comment]
The next release should handle such errors properly to at least fallback to project selection/creation dialog.
