### ISSUE TITLE
crash on the "Outline" section

### ISSUE THREAD

**Issue by LonelyMusicDisc** [olivierkes/manuskript#1032]
I was enjoying the program as per usual and then boom. I'm not sure what caused it, but it looks like me slightly changing the theme messed it up.

```python
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 32, in paint
    iconRect = style.subElementRect(style.SE_ItemViewItemDecoration, opt)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 32, in paint
    iconRect = style.subElementRect(style.SE_ItemViewItemDecoration, opt)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Fatal Python error: Segmentation fault

Thread 0x00007f4f93fff700 (most recent call first):
  File "/home/zeney/.local/lib/python3.8/site-packages/language_tool_python/server.py", line 319 in _consume
  File "/home/zeney/.local/lib/python3.8/site-packages/language_tool_python/server.py", line 267 in <lambda>
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f4fbb643740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 243 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 309 in run
  File "/usr/bin/manuskript", line 30 in <module>
Segmentation fault (core dumped)
```

**Comment by TheJackiMonster** [comment]
If you are using a custom Qt theme, that is probably the cause of this.

**Comment by LonelyMusicDisc** [comment]
you're right, a shame :pensive:
