### ISSUE TITLE
Search no longer works

### ISSUE THREAD

**Issue by jrstrick** [olivierkes/manuskript#1095]
As of the develop branch pulled on December 22,2022, the search function crashes Manuskript every time I try to use it. Regex seems to choke on the search string (which was *the* in this example, minus the asterisks.) It throws the following error:

  File "/home/jim/manuskript/bin/../manuskript/functions/__init__.py", line 472, in search
    return [(m.start(), m.end(), getSearchResultContext(text, m.start(), m.end())) for m in searchRegex.finditer(text)]
TypeError: expected string or bytes-like object

Full dump follows. Some file names have been edited out to protect the innocent. I'm unclear what's causing the 'strange things in file' errors. Are my directories out of sync with the folder's metadata file?

```
Logging to STDERR.
Logging to file: /home/jim/.local/share/manuskript/manuskript/logs/2022-12-23_16-45-31_manuskript#52369.log
Operating System: Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35
Hardware: x86_64 / x86_64
Running from unpackaged source code.
* sys.executable = '/usr/bin/python3'
* sys.argv = ['/home/jim/bin/manuskript']
* sys.path = ['/home/jim/manuskript/bin',
 '/home/jim/manuskript/bin/..',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/home/jim/.local/lib/python3.10/site-packages',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages']
* sys.prefix = '/usr'
Manuskript 0.14.0#a36bc55 (Python 3.10.6)
* PyQt 5.15.6 (compiled against Qt 5.15.3)
  * Qt 5.15.3 (runtime)
* lxml.etree 4.8.0.0
  * libxml   2.9.13 (compiled: 2.9.13)
  * libxslt  1.1.34 (compiled: 1.1.34)
* pyEnchant N/A (libenchant: N/A)
* pySpellChecker N/A
* Symspellpy N/A
* Markdown 3.3.6
Web rendering engine: QTextEdit
Preferred translation: ['en'] (based on available ui languages)
No translation found or loaded. (manuskript_en.qm)
Using the builtin translation. (U.S. English)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
Loading: /home/jim/Dropbox/Poltergeist Stories/p2-Dead of Winter.msk
Detected file format version: 1. Zip: False.
Loading /home/jim/Dropbox/Poltergeist Stories/p2-Dead of Winter.msk (folder)
Reading labels:
* Add status: Idea (#ffff00)
* Add status: Note (#00ff00)
* Add status: Chapter (#0000ff)
* Add status: Scene (#ff0000)
* Add status: Research (#00ffff)
* Add status: Blocking (#c061cb)
Reading status:
* Add status: TODO
* Add status: First draft
* Add status: Second draft
* Add status: Final
Reading plots:
* Add plot: The Murder
* Add plot: Nina and Cronenberg
* Add plot: The Case
* Add plot: <redacted>
Reading World:
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>
* Add worldItem: <redacted>t
Reading Characters:
* Adds Nina Cohen (0)
* Adds Viviana Cazacu aka: the body (1)
* Adds Drew MacLeod (10)
* Adds Mirikit Berry (11)
* Adds Tom Fletcher (12)
* Adds Brenda the Witch (13)
* Adds Jenny Thordarson (14)
* Adds Sandy Donald (15)
* Adds Jinn (the cat) (2)
* Adds Odessa (3)
* Adds Gideon Cronenberg (4)
* Adds The Lawgiver (5)
* Adds John (Long Jack) Calahan (6)
* Adds Nikita (Niki) Zapata (7)
* Adds Morgan Whitney (9)
Reading outline:
* Adds 0-Acknowledgements to Root (folder)
* Adds 0-<redacted>.md to Acknowledgements (file)
Strange things in file 0-Acknowledgements
* Adds 1-Chapters to Root (folder)
* Adds 00-Chapter_1 to Chapters (folder)
  * Adds 0-<redacted>.md to Chapter 1 (file)
  * Adds 1-<redacted>.md to Chapter 1 (file)
  * Adds 2-<redacted>.md to Chapter 1 (file)
Strange things in file 00-Chapter_1
* Adds 01-Chapter_2 to Chapters (folder)
  * Adds 0-<redacted>.md to Chapter 2 (file)
  * Adds 1-<redacted>.md to Chapter 2 (file)
Strange things in file 01-Chapter_2
* Adds 02-Who_Is-Was_Niki_Zapata to Chapters (folder)
  * Adds 0-<redacted>.md to Who Is/Was Niki Zapata (file)
Strange things in file 02-Who_Is-Was_Niki_Zapata
* Adds 03-Stake_Out to Chapters (folder)
Strange things in file 03-Stake_Out
* Adds 04-The_Omega_Friend to Chapters (folder)
Strange things in file 04-The_Omega_Friend
* Adds 05-Sightings to Chapters (folder)
Strange things in file 05-Sightings
* Adds 06-Dead_Girl-s_Body_by_the_Railroad_Track to Chapters (folder)
Strange things in file 06-Dead_Girl-s_Body_by_the_Railroad_Track
* Adds 07-Team_Spirit to Chapters (folder)
Strange things in file 07-Team_Spirit
* Adds 08-The_Winter_Formal to Chapters (folder)
Strange things in file 08-The_Winter_Formal
* Adds 09-Will_o-_the_Wisp to Chapters (folder)
Strange things in file 09-Will_o-_the_Wisp
* Adds 10-What_Are_you--What_am_I- to Chapters (folder)
Strange things in file 10-What_Are_you--What_am_I-
* Adds 11-Who_-Re-animated_Roger_Rabbit- to Chapters (folder)
Strange things in file 11-Who_-Re-animated_Roger_Rabbit-
* Adds 12-On_a_Cold_Winter-s_Night to Chapters (folder)
  * Adds 0-<redacted>.md to On a Cold Winter's Night (file)
  * Adds 1-<redacted>.md to On a Cold Winter's Night (file)
Strange things in file 12-On_a_Cold_Winter-s_Night
Strange things in file 1-Chapters
Project /home/jim/Dropbox/Poltergeist Stories/p2-Dead of Winter.msk loaded.
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
An unhandled exception has occurred!
Traceback (most recent call last):
  File "/home/jim/manuskript/bin/../manuskript/ui/search.py", line 142, in search
    results += model.searchOccurrences(searchRegex, filteredColumns)
  File "/home/jim/manuskript/bin/../manuskript/models/searchableModel.py", line 11, in searchOccurrences
    results += item.searchOccurrences(searchRegex, column)
  File "/home/jim/manuskript/bin/../manuskript/models/characterModel.py", line 365, in searchOccurrences
    results += super().searchOccurrences(searchRegex, column)
  File "/home/jim/manuskript/bin/../manuskript/models/searchableItem.py", line 16, in searchOccurrences
    return [self.wrapSearchOccurrence(column, startPos, endPos, context) for (startPos, endPos, context) in search(searchRegex, self.searchData(column))]
  File "/home/jim/manuskript/bin/../manuskript/functions/__init__.py", line 472, in search
    return [(m.start(), m.end(), getSearchResultContext(text, m.start(), m.end())) for m in searchRegex.finditer(text)]
TypeError: expected string or bytes-like object
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/home/jim/manuskript/bin/../manuskript/ui/search.py", line 142, in search
    results += model.searchOccurrences(searchRegex, filteredColumns)
  File "/home/jim/manuskript/bin/../manuskript/models/searchableModel.py", line 11, in searchOccurrences
    results += item.searchOccurrences(searchRegex, column)
  File "/home/jim/manuskript/bin/../manuskript/models/characterModel.py", line 365, in searchOccurrences
    results += super().searchOccurrences(searchRegex, column)
  File "/home/jim/manuskript/bin/../manuskript/models/searchableItem.py", line 16, in searchOccurrences
    return [self.wrapSearchOccurrence(column, startPos, endPos, context) for (startPos, endPos, context) in search(searchRegex, self.searchData(column))]
  File "/home/jim/manuskript/bin/../manuskript/functions/__init__.py", line 472, in search
    return [(m.start(), m.end(), getSearchResultContext(text, m.start(), m.end())) for m in searchRegex.finditer(text)]
TypeError: expected string or bytes-like object
jim@lucky:~$ 
```

**Comment by TheShadowOfHassen** [comment]
So I found the problem too. It doesn't have anything to do with the "Strange things" error. That I had too in my folder/ file manuskript file but my .msk compressed version didn't. Whatever that "Strange things" is I have no clue. I figured out a way to fix the "TypeError: expected string or bytes-like object"  and will make a pull request.

**Comment by jrstrick** [comment]
the PR above (when I patched my own copy manually) fixed the problem.

**Comment by TheJackiMonster** [comment]
The fix got merged. So the next release will solve the issue.

**Comment by TheShadowOfHassen** [comment]
Great! @jrstrick could you please close the issue? Thanks!

**Comment by jrstrick** [comment]
Fixed.
