### ISSUE TITLE
Flatpak Manuskript crashing when trying to put a folder inside another folder

### ISSUE THREAD

**Issue by MrQvest** [olivierkes/manuskript#1193]
grabbing a folder with the mouse and hovering it over another item in the editor crashes Manuskript with a python error. I don't have many details as of now but I will elaborate further when I can

Platform: Flatpak
OS: Fedora Linux 38

**Comment by TheShadowOfHassen** [comment]
So have you tested the non flatpak version of manuskript?  Does that work?

**Comment by MrQvest** [comment]
Just tested with the RPM package. It doesn't have this bug. Weird. Works as expected with the RPM package

**Comment by MrQvest** [comment]
One more thing. I did a flatpak run from commandline. This is what I got as the error:

> CRITICAL> An unhandled exception has occurred!
> Traceback (most recent call last):
>   File "/app/lib/manuskript/manuskript/models/abstractModel.py", line 316, in canDropMimeData
>     items = self.decodeMimeData(data)
>   File "/app/lib/manuskript/manuskript/models/abstractModel.py", line 367, in decodeMimeData
>     item = outlineItem(xml=ET.tostring(child))
>   File "/app/lib/manuskript/manuskript/models/outlineItem.py", line 37, in __init__
>     abstractItem.__init__(self, model, title, _type, xml, parent, ID)
>   File "/app/lib/manuskript/manuskript/models/abstractItem.py", line 45, in __init__
>     self.setFromXML(xml)
>   File "/app/lib/manuskript/manuskript/models/abstractItem.py", line 319, in setFromXML
>     root = ET.XML(xml)
>   File "src/lxml/etree.pyx", line 3216, in lxml.etree.XML
>   File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
>   File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
>   File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
>   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
>   File "<string>", line 1
> lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 1, column 76720


Should have done that from the beginning, sorry for not thinking about this earlier
