### ISSUE TITLE
DictNotFoundError when dict language specified in settings is not installed

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#12]
DictNotFoundError when dict language specified in settings is not installed, but PyEnchant is installed.

```
Traceback (most recent call last):
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/mainWindow.py", line 910, in toggleSpellcheck
    w.toggleSpellcheck(val)
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/ui/views/textEditView.py", line 405, in toggleSpellcheck
    self._dict = enchant.Dict(self.currentDict if self.currentDict else enchant.get_default_language())
  File "/usr/lib/python3/dist-packages/enchant/__init__.py", line 502, in __init__
    self._switch_this(broker._request_dict_data(tag),broker)
  File "/usr/lib/python3/dist-packages/enchant/__init__.py", line 264, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "/usr/lib/python3/dist-packages/enchant/__init__.py", line 218, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'fr_CH' could not be found
```

**Comment by olivierkes** [comment]
Fixed.
