### ISSUE TITLE
Cannot start Manuskript on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by jytou** [olivierkes/manuskript#1203]
Installed Manuskript through the .deb installation. When launching Manuskript, I get the following error:

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
```

FYI, the default python on my machine is Ubuntu's default: 3.10.12
I have tried with python 3.9, 3.10 and 3.11, and qt versions 5.5.13 to 5.5.15, same issue. I suppose I would need a different (older?) version of qt, but I wonder which one. I couldn't find any specific requirements for the python version or the Qt version either, which I believe would be helpful to troubleshoot that kind of issues. :)

**Comment by TheJackiMonster** [comment]
Try the latest release of Manuskript. It should have been fixed already.

**Comment by bufalo1973** [comment]
FYI, Ubuntu Jammy still uses 0.12.1.
