### ISSUE TITLE
Crash on Chapter Move

### ISSUE THREAD

**Issue by abparr** [olivierkes/manuskript#1216]
Running latest on Linux Mint, when I attempt to move a new chapter from the bottom of the list up the sequence, the software crashes. Copying and pasting the folder (Chapter) also crashes. It does not happen for empty, unpopulated, chapters.

**Comment by obw** [comment]
Which Version, I have recently switched too Mint, and Distro Manuskript Version, was old!

* System Packet 0.12.0-1
* Flatpack 0.15.0

I prefer to use the development tree. I update it every now and then, mostly when the coders have delivered great work again!

The Problem you describe, is known in older Versions!

If you use Faltpack with the actual Release 0.15.0, then try the development tree! When the Problem happens there also, we need more Information to track the Bug down!

If, after an update, everything works, like planned, pleas close this Ticket!

Regards

**Comment by TheShadowOfHassen** [comment]
Mint is based on the latest ubuntu LTS, and the manuskript from it will be really old.

I prefer the .deb file from the website for ubuntu based because with it you can install new spell check languages and LanguageTool. The flatpak I don't think can.

**Comment by abparr** [comment]
Linux Mint 21.2 Cinnamon
Kernel 5.15.0-83-generic

Manuskript:
Version 0.15.0


Thanks, I will give that a go and see where that takes me.  I worked around it by creating a new chapter and moving the empty one, renaming it, and then cut/pasting the scenes from the one that was stuck at the bottom of the sequence.

**Comment by obw** [comment]
> Linux Mint 21.2 Cinnamon Kernel 5.15.0-83-generic
> 
> Manuskript: Version 0.15.0
Looks like the actual stable of Manuskript, I use the same Mint Version, so some Information for our Python Team:

* Python 3.10.12
* PyQt 5.15.6
* Qt 5.15.3
 
Which Language do you use and which file system, when you doesn't change anything, it should be ext4! So normally should there nor Problem!

It's possible for you, to start manuskript this way:

`manuskript -v -L manuskript.log`

Then try to reproduce the Crash, after crashing, have a little look into `manuskript.log` and remove everything which is privacy related, then upload it in this Ticket, so the People with knowledge (_Also known as **MAGIC**_), can find the Problem!
> 
> Thanks, I will give that a go and see where that takes me. I worked around it by creating a new chapter and moving the empty one, renaming it, and then cut/pasting the scenes from the one that was stuck at the bottom of the sequence.


_I will also open a Ticket, with the Target, to make something like this easier for all participants! Manuskript really need Template for Tickets!_

**Comment by abparr** [comment]
Python 3.10.12
EXT4

I get errors when I try to run it from the term saying that it isn't installed, so I thought it was the Flatpack, but I checked my installed Flatpaks to see what the dot dot name was, it wasn't there.  The software is installed through the Linux Mint Software Manager.  I have never seen this before.  Very odd.  I may pull the Software Manager version and grab the deb.

**Comment by abparr** [comment]
This is the deb crash report when I attempt to open it, which is a different release than the last one I was using, trying the Flatpak next:  (this has nothing to so with my original issue)

INFO> Logging to file: manuskript.log
INFO> Operating System: Linux-5.15.0-83-generic-x86_64-with-glibc2.35
INFO> Hardware: x86_64 / x86_64
INFO> Running from unpackaged source code.
INFO> Manuskript 0.12.0 (Python 3.10.12)
INFO> * PyQt 5.15.6 (compiled against Qt 5.15.3)
INFO>   * Qt 5.15.3 (runtime)
INFO> * lxml.etree 4.8.0.0
INFO>   * libxml   2.9.13 (compiled: 2.9.13)
INFO>   * libxslt  1.1.34 (compiled: 1.1.34)
INFO> * pyEnchant 3.2.0 (libenchant: 2.3.2)
INFO> * pySpellChecker N/A
INFO> * Symspellpy N/A
INFO> * Markdown 3.3.6
INFO> Web rendering engine: QtWebKit
INFO> Preferred translation: ['en-US'] (based on available ui languages)
INFO> Using the builtin translation. (U.S. English)
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'

**Comment by abparr** [comment]
Pulled the deb and added the Flatpak manually. Loads fine.

Here is the crash report when I try and move a Chapter.

flatpak run ch.theologeek.Manuskript -v -L manuskript.log
3.9.9 (main, Nov 10 2011, 15:00:00) 
[GCC 11.3.0]
<module 'PyQt5.QtWebEngineWidgets' from '/app/lib/python3.9/site-packages/PyQt5/QtWebEngineWidgets.abi3.so'>
2023-09-14 10:53:09,598 DEBUG:Logging to STDERR.
Gtk-Message: 10:53:09.613: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
2023-09-14 10:53:09,679 INFO:Logging to file: manuskript.log
INFO> Logging to file: manuskript.log
2023-09-14 10:53:09,684 INFO:Operating System: Linux-5.15.0-83-generic-x86_64-with-glibc2.33
INFO> Operating System: Linux-5.15.0-83-generic-x86_64-with-glibc2.33
2023-09-14 10:53:09,684 INFO:Hardware: x86_64 / 
INFO> Hardware: x86_64 / 
2023-09-14 10:53:09,684 INFO:Running from unpackaged source code.
INFO> Running from unpackaged source code.
2023-09-14 10:53:09,684 DEBUG:* sys.executable = '/usr/bin/python3'
2023-09-14 10:53:09,684 DEBUG:* sys.argv = ['/app/bin/manuskript', '-v', '-L', 'manuskript.log']
2023-09-14 10:53:09,684 DEBUG:* sys.path = ['/app/bin',
 '/app/lib/manuskript',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/lib/python3.9/site-packages',
 '/app/lib/python3.9/site-packages']
2023-09-14 10:53:09,684 DEBUG:* sys.prefix = '/usr'
2023-09-14 10:53:09,689 INFO:Manuskript 0.15.0 (Python 3.9.9)
INFO> Manuskript 0.15.0 (Python 3.9.9)
2023-09-14 10:53:09,689 INFO:* PyQt 5.15.6 (compiled against Qt 5.15.8)
INFO> * PyQt 5.15.6 (compiled against Qt 5.15.8)
2023-09-14 10:53:09,689 INFO:  * Qt 5.15.8 (runtime)
INFO>   * Qt 5.15.8 (runtime)
2023-09-14 10:53:09,696 INFO:* lxml.etree 4.6.4.0
INFO> * lxml.etree 4.6.4.0
2023-09-14 10:53:09,696 INFO:  * libxml   2.9.12 (compiled: 2.9.12)
INFO>   * libxml   2.9.12 (compiled: 2.9.12)
2023-09-14 10:53:09,696 INFO:  * libxslt  1.1.34 (compiled: 1.1.34)
INFO>   * libxslt  1.1.34 (compiled: 1.1.34)
2023-09-14 10:53:09,696 INFO:* pyEnchant 3.2.2 (libenchant: 2.3.4)
INFO> * pyEnchant 3.2.2 (libenchant: 2.3.4)
2023-09-14 10:53:09,696 INFO:* pySpellChecker 0.6.2
INFO> * pySpellChecker 0.6.2
2023-09-14 10:53:09,696 INFO:* Symspellpy 6.7.5
INFO> * Symspellpy 6.7.5
2023-09-14 10:53:09,728 INFO:* Markdown 3.3.7
INFO> * Markdown 3.3.7
2023-09-14 10:53:09,728 INFO:Web rendering engine: QtWebEngine
INFO> Web rendering engine: QtWebEngine
2023-09-14 10:53:09,736 INFO:Preferred translation: ['en-US', 'en', 'en-Latn-US'] (based on available ui languages)
INFO> Preferred translation: ['en-US', 'en', 'en-Latn-US'] (based on available ui languages)
2023-09-14 10:53:09,736 INFO:Using the builtin translation. (U.S. English)
INFO> Using the builtin translation. (U.S. English)
2023-09-14 10:53:10,038 INFO:Loading: /home/anthony/Dropbox/The Last Stop/The Last Stop backup.msk
INFO> Loading: /home/anthony/Dropbox/The Last Stop/The Last Stop backup.msk
2023-09-14 10:53:10,038 INFO:Detected file format version: 1. Zip: True.
INFO> Detected file format version: 1. Zip: True.
2023-09-14 10:53:10,038 DEBUG:Loading /home/anthony/Dropbox/The Last Stop/The Last Stop backup.msk (zip)
2023-09-14 10:53:10,044 DEBUG:Reading labels:
2023-09-14 10:53:10,044 DEBUG:* Add status: Idea (#ffff00)
2023-09-14 10:53:10,044 DEBUG:* Add status: Note (#00ff00)
2023-09-14 10:53:10,044 DEBUG:* Add status: Chapter (#0000ff)
2023-09-14 10:53:10,045 DEBUG:* Add status: Scene (#ff0000)
2023-09-14 10:53:10,045 DEBUG:* Add status: Research (#00ffff)
2023-09-14 10:53:10,045 DEBUG:Reading status:
2023-09-14 10:53:10,045 DEBUG:* Add status: TODO
2023-09-14 10:53:10,045 DEBUG:* Add status: First draft
2023-09-14 10:53:10,045 DEBUG:* Add status: Second draft
2023-09-14 10:53:10,045 DEBUG:* Add status: Final
2023-09-14 10:53:10,045 DEBUG:Reading plots:
2023-09-14 10:53:10,045 DEBUG:* Add plot: Haunted House
2023-09-14 10:53:10,046 DEBUG:* Add plot: Sarah's Past
2023-09-14 10:53:10,046 DEBUG:* Add plot: William's Failures
2023-09-14 10:53:10,046 DEBUG:* Add plot: Mary's Growth
2023-09-14 10:53:10,046 DEBUG:* Add plot: Edward's Growth
2023-09-14 10:53:10,046 DEBUG:Reading World:
2023-09-14 10:53:10,046 DEBUG:* Add worldItem: Abadonded Town in the Old West 1800s
2023-09-14 10:53:10,046 DEBUG:Reading Characters:
2023-09-14 10:53:10,046 DEBUG:* Adds William Capehart (0)
2023-09-14 10:53:10,047 DEBUG:* Adds Sarah Weston Capehart (1)
2023-09-14 10:53:10,047 DEBUG:* Adds Peter Paetz (2)
2023-09-14 10:53:10,047 DEBUG:* Adds Mary Capehart (3)
2023-09-14 10:53:10,047 DEBUG:* Adds Edward Capehart (4)
2023-09-14 10:53:10,047 DEBUG:* Adds The Building (5)
2023-09-14 10:53:10,048 DEBUG:* Adds Timothy Rearden (6)
2023-09-14 10:53:10,048 DEBUG:Reading outline:
2023-09-14 10:53:10,048 DEBUG:* Adds 00-Chapter_1 to Root (folder)
2023-09-14 10:53:10,048 DEBUG:* Adds 0-Scene_1.md to Chapter 1 (file)
2023-09-14 10:53:10,050 DEBUG:* Adds 1-Scene_2.md to Chapter 1 (file)
2023-09-14 10:53:10,051 DEBUG:* Adds 2-Scene_3.md to Chapter 1 (file)
2023-09-14 10:53:10,052 DEBUG:* Adds 3-Scene_4.md to Chapter 1 (file)
2023-09-14 10:53:10,053 DEBUG:* Adds 4-Scene_5.md to Chapter 1 (file)
2023-09-14 10:53:10,055 DEBUG:Strange things in file 00-Chapter_1
2023-09-14 10:53:10,055 DEBUG:* Adds 01-Chapter_2 to Root (folder)
2023-09-14 10:53:10,055 DEBUG:* Adds 0-Scene_1.md to Chapter 2 (file)
2023-09-14 10:53:10,056 DEBUG:* Adds 1-Scene_2.md to Chapter 2 (file)
2023-09-14 10:53:10,058 DEBUG:* Adds 2-Scene_3.md to Chapter 2 (file)
2023-09-14 10:53:10,059 DEBUG:* Adds 3-Scene_4.md to Chapter 2 (file)
2023-09-14 10:53:10,060 DEBUG:* Adds 4-Scene_5.md to Chapter 2 (file)
2023-09-14 10:53:10,061 DEBUG:Strange things in file 01-Chapter_2
2023-09-14 10:53:10,061 DEBUG:* Adds 02-Chapter_3 to Root (folder)
2023-09-14 10:53:10,061 DEBUG:* Adds 0-Scene_1.md to Chapter 3 (file)
2023-09-14 10:53:10,063 DEBUG:* Adds 1-Scene_2.md to Chapter 3 (file)
2023-09-14 10:53:10,064 DEBUG:* Adds 2-Scene_3.md to Chapter 3 (file)
2023-09-14 10:53:10,065 DEBUG:* Adds 3-Scene_4.md to Chapter 3 (file)
2023-09-14 10:53:10,066 DEBUG:* Adds 4-Scene_5.md to Chapter 3 (file)
2023-09-14 10:53:10,067 DEBUG:Strange things in file 02-Chapter_3
2023-09-14 10:53:10,067 DEBUG:* Adds 03-Chapter_4 to Root (folder)
2023-09-14 10:53:10,068 DEBUG:* Adds 0-Scene_1.md to Chapter 4 (file)
2023-09-14 10:53:10,069 DEBUG:* Adds 1-Scene_2.md to Chapter 4 (file)
2023-09-14 10:53:10,071 DEBUG:* Adds 2-Scene_3.md to Chapter 4 (file)
2023-09-14 10:53:10,072 DEBUG:* Adds 3-Scene_4.md to Chapter 4 (file)
2023-09-14 10:53:10,073 DEBUG:* Adds 4-Scene_5.md to Chapter 4 (file)
2023-09-14 10:53:10,074 DEBUG:Strange things in file 03-Chapter_4
2023-09-14 10:53:10,074 DEBUG:* Adds 04-Chapter_5 to Root (folder)
2023-09-14 10:53:10,074 DEBUG:* Adds 0-Scene_1.md to Chapter 5 (file)
2023-09-14 10:53:10,076 DEBUG:* Adds 1-Scene_2.md to Chapter 5 (file)
2023-09-14 10:53:10,077 DEBUG:* Adds 2-Scene_3.md to Chapter 5 (file)
2023-09-14 10:53:10,078 DEBUG:* Adds 3-Scene_4.md to Chapter 5 (file)
2023-09-14 10:53:10,079 DEBUG:* Adds 4-Scene_5.md to Chapter 5 (file)
2023-09-14 10:53:10,081 DEBUG:Strange things in file 04-Chapter_5
2023-09-14 10:53:10,081 DEBUG:* Adds 05-Chapter_6 to Root (folder)
2023-09-14 10:53:10,081 DEBUG:* Adds 0-Scene_1.md to Chapter 6 (file)
2023-09-14 10:53:10,082 DEBUG:* Adds 1-Scene_2.md to Chapter 6 (file)
2023-09-14 10:53:10,083 DEBUG:* Adds 2-Scene_3.md to Chapter 6 (file)
2023-09-14 10:53:10,085 DEBUG:* Adds 3-Scene_4.md to Chapter 6 (file)
2023-09-14 10:53:10,086 DEBUG:* Adds 4-Scene_5.md to Chapter 6 (file)
2023-09-14 10:53:10,087 DEBUG:Strange things in file 05-Chapter_6
2023-09-14 10:53:10,087 DEBUG:* Adds 06-Chapter_7 to Root (folder)
2023-09-14 10:53:10,087 DEBUG:* Adds 0-Scene_1.md to Chapter 7 (file)
2023-09-14 10:53:10,089 DEBUG:* Adds 1-Scene_2.md to Chapter 7 (file)
2023-09-14 10:53:10,090 DEBUG:* Adds 2-Scene_3.md to Chapter 7 (file)
2023-09-14 10:53:10,091 DEBUG:* Adds 3-Scene_4.md to Chapter 7 (file)
2023-09-14 10:53:10,092 DEBUG:* Adds 4-Scene_5.md to Chapter 7 (file)
2023-09-14 10:53:10,093 DEBUG:Strange things in file 06-Chapter_7
2023-09-14 10:53:10,093 DEBUG:* Adds 07-Chapter_8 to Root (folder)
2023-09-14 10:53:10,094 DEBUG:* Adds 0-Scene_1.md to Chapter 8 (file)
2023-09-14 10:53:10,095 DEBUG:* Adds 1-Scene_2.md to Chapter 8 (file)
2023-09-14 10:53:10,096 DEBUG:* Adds 2-Scene_3.md to Chapter 8 (file)
2023-09-14 10:53:10,097 DEBUG:* Adds 3-Scene_4.md to Chapter 8 (file)
2023-09-14 10:53:10,099 DEBUG:* Adds 4-Scene_5.md to Chapter 8 (file)
2023-09-14 10:53:10,100 DEBUG:Strange things in file 07-Chapter_8
2023-09-14 10:53:10,100 DEBUG:* Adds 08-Chapter_9 to Root (folder)
2023-09-14 10:53:10,100 DEBUG:* Adds 0-Scene_1.md to Chapter 9 (file)
2023-09-14 10:53:10,101 DEBUG:* Adds 1-Scene_2.md to Chapter 9 (file)
2023-09-14 10:53:10,103 DEBUG:* Adds 2-Scene_3.md to Chapter 9 (file)
2023-09-14 10:53:10,104 DEBUG:* Adds 3-Scene_4.md to Chapter 9 (file)
2023-09-14 10:53:10,105 DEBUG:* Adds 4-Scene_5.md to Chapter 9 (file)
2023-09-14 10:53:10,107 DEBUG:Strange things in file 08-Chapter_9
2023-09-14 10:53:10,107 DEBUG:* Adds 09-Chapter_10 to Root (folder)
2023-09-14 10:53:10,107 DEBUG:* Adds 0-Scene_1.md to Chapter 10 (file)
2023-09-14 10:53:10,108 DEBUG:* Adds 1-Scene_2.md to Chapter 10 (file)
2023-09-14 10:53:10,109 DEBUG:* Adds 2-Scene_3.md to Chapter 10 (file)
2023-09-14 10:53:10,111 DEBUG:* Adds 3-Scene_4.md to Chapter 10 (file)
2023-09-14 10:53:10,112 DEBUG:* Adds 4-Scene_5.md to Chapter 10 (file)
2023-09-14 10:53:10,113 DEBUG:Strange things in file 09-Chapter_10
2023-09-14 10:53:10,114 DEBUG:* Adds 10-Chapter_11 to Root (folder)
2023-09-14 10:53:10,114 DEBUG:* Adds 0-Scene_1.md to Chapter 11 (file)
2023-09-14 10:53:10,115 DEBUG:* Adds 1-Scene_2.md to Chapter 11 (file)
2023-09-14 10:53:10,116 DEBUG:* Adds 2-Scene_3.md to Chapter 11 (file)
2023-09-14 10:53:10,118 DEBUG:* Adds 3-Scene_4.md to Chapter 11 (file)
2023-09-14 10:53:10,119 DEBUG:* Adds 4-Scene_5.md to Chapter 11 (file)
2023-09-14 10:53:10,120 DEBUG:Strange things in file 10-Chapter_11
2023-09-14 10:53:10,120 DEBUG:* Adds 11-Chapter_12 to Root (folder)
2023-09-14 10:53:10,121 DEBUG:* Adds 0-Scene_1.md to Chapter 12 (file)
2023-09-14 10:53:10,122 DEBUG:* Adds 1-Scene_2.md to Chapter 12 (file)
2023-09-14 10:53:10,123 DEBUG:* Adds 2-Scene_3.md to Chapter 12 (file)
2023-09-14 10:53:10,125 DEBUG:* Adds 3-Scene_4.md to Chapter 12 (file)
2023-09-14 10:53:10,126 DEBUG:* Adds 4-Scene_5.md to Chapter 12 (file)
2023-09-14 10:53:10,127 DEBUG:Strange things in file 11-Chapter_12
2023-09-14 10:53:10,127 DEBUG:* Adds 12-Chapter_13 to Root (folder)
2023-09-14 10:53:10,128 DEBUG:* Adds 0-Scene_1.md to Chapter 13 (file)
2023-09-14 10:53:10,129 DEBUG:* Adds 1-Scene_2.md to Chapter 13 (file)
2023-09-14 10:53:10,130 DEBUG:* Adds 2-Scene_3.md to Chapter 13 (file)
2023-09-14 10:53:10,131 DEBUG:* Adds 3-Scene_4.md to Chapter 13 (file)
2023-09-14 10:53:10,133 DEBUG:* Adds 4-Scene_5.md to Chapter 13 (file)
2023-09-14 10:53:10,134 DEBUG:Strange things in file 12-Chapter_13
2023-09-14 10:53:10,134 DEBUG:* Adds 13-Chapter_14 to Root (folder)
2023-09-14 10:53:10,134 DEBUG:* Adds 0-Scene_1.md to Chapter 14 (file)
2023-09-14 10:53:10,135 DEBUG:* Adds 1-Scene_2.md to Chapter 14 (file)
2023-09-14 10:53:10,136 DEBUG:* Adds 2-Scene_3.md to Chapter 14 (file)
2023-09-14 10:53:10,136 DEBUG:* Adds 3-Scene_4.md to Chapter 14 (file)
2023-09-14 10:53:10,137 DEBUG:* Adds 4-Scene_5.md to Chapter 14 (file)
2023-09-14 10:53:10,138 DEBUG:Strange things in file 13-Chapter_14
2023-09-14 10:53:10,138 DEBUG:* Adds 14-Chapter_15 to Root (folder)
2023-09-14 10:53:10,138 DEBUG:* Adds 0-Scene_1.md to Chapter 15 (file)
2023-09-14 10:53:10,139 DEBUG:* Adds 1-Scene_2.md to Chapter 15 (file)
2023-09-14 10:53:10,140 DEBUG:* Adds 2-Scene_3.md to Chapter 15 (file)
2023-09-14 10:53:10,141 DEBUG:* Adds 3-Scene_4.md to Chapter 15 (file)
2023-09-14 10:53:10,141 DEBUG:* Adds 4-Scene_5.md to Chapter 15 (file)
2023-09-14 10:53:10,142 DEBUG:Strange things in file 14-Chapter_15
2023-09-14 10:53:10,142 DEBUG:* Adds 15-Chapter_16 to Root (folder)
2023-09-14 10:53:10,142 DEBUG:* Adds 0-Scene_1.md to Chapter 16 (file)
2023-09-14 10:53:10,143 DEBUG:* Adds 1-Scene_2.md to Chapter 16 (file)
2023-09-14 10:53:10,144 DEBUG:* Adds 2-Scene_3.md to Chapter 16 (file)
2023-09-14 10:53:10,145 DEBUG:* Adds 3-Scene_4.md to Chapter 16 (file)
2023-09-14 10:53:10,146 DEBUG:* Adds 4-Scene_5.md to Chapter 16 (file)
2023-09-14 10:53:10,146 DEBUG:Strange things in file 15-Chapter_16
2023-09-14 10:53:10,146 DEBUG:* Adds 16-Chapter_17 to Root (folder)
2023-09-14 10:53:10,147 DEBUG:* Adds 0-Scene_1.md to Chapter 17 (file)
2023-09-14 10:53:10,147 DEBUG:* Adds 1-Scene_2.md to Chapter 17 (file)
2023-09-14 10:53:10,148 DEBUG:* Adds 2-Scene_3.md to Chapter 17 (file)
2023-09-14 10:53:10,149 DEBUG:* Adds 3-Scene_4.md to Chapter 17 (file)
2023-09-14 10:53:10,150 DEBUG:* Adds 4-Scene_5.md to Chapter 17 (file)
2023-09-14 10:53:10,151 DEBUG:Strange things in file 16-Chapter_17
2023-09-14 10:53:10,151 DEBUG:* Adds 17-Chapter_18 to Root (folder)
2023-09-14 10:53:10,151 DEBUG:* Adds 0-Scene_1.md to Chapter 18 (file)
2023-09-14 10:53:10,152 DEBUG:* Adds 1-Scene_2.md to Chapter 18 (file)
2023-09-14 10:53:10,153 DEBUG:* Adds 2-Scene_3.md to Chapter 18 (file)
2023-09-14 10:53:10,153 DEBUG:* Adds 3-Scene_4.md to Chapter 18 (file)
2023-09-14 10:53:10,154 DEBUG:* Adds 4-Scene_5.md to Chapter 18 (file)
2023-09-14 10:53:10,155 DEBUG:Strange things in file 17-Chapter_18
2023-09-14 10:53:10,155 DEBUG:* Adds 18-Chapter_19 to Root (folder)
2023-09-14 10:53:10,155 DEBUG:* Adds 0-Scene_1.md to Chapter 19 (file)
2023-09-14 10:53:10,156 DEBUG:* Adds 1-Scene_2.md to Chapter 19 (file)
2023-09-14 10:53:10,157 DEBUG:* Adds 2-Scene_3.md to Chapter 19 (file)
2023-09-14 10:53:10,158 DEBUG:* Adds 3-Scene_4.md to Chapter 19 (file)
2023-09-14 10:53:10,158 DEBUG:* Adds 4-Scene_5.md to Chapter 19 (file)
2023-09-14 10:53:10,159 DEBUG:Strange things in file 18-Chapter_19
2023-09-14 10:53:10,159 DEBUG:* Adds 19-Chapter_20 to Root (folder)
2023-09-14 10:53:10,160 DEBUG:* Adds 0-Scene_1.md to Chapter 20 (file)
2023-09-14 10:53:10,160 DEBUG:* Adds 1-Scene_2.md to Chapter 20 (file)
2023-09-14 10:53:10,161 DEBUG:* Adds 2-Scene_3.md to Chapter 20 (file)
2023-09-14 10:53:10,162 DEBUG:* Adds 3-Scene_4.md to Chapter 20 (file)
2023-09-14 10:53:10,163 DEBUG:* Adds 4-Scene_5.md to Chapter 20 (file)
2023-09-14 10:53:10,164 DEBUG:Strange things in file 19-Chapter_20
2023-09-14 10:53:10,165 INFO:Project /home/anthony/Dropbox/The Last Stop/The Last Stop backup.msk loaded.
INFO> Project /home/anthony/Dropbox/The Last Stop/The Last Stop backup.msk loaded.
2023-09-14 10:53:33,212 CRITICAL:An unhandled exception has occurred!
Traceback (most recent call last):
  File "/app/lib/manuskript/manuskript/models/abstractModel.py", line 316, in canDropMimeData
    items = self.decodeMimeData(data)
  File "/app/lib/manuskript/manuskript/models/abstractModel.py", line 367, in decodeMimeData
    item = outlineItem(xml=ET.tostring(child))
  File "/app/lib/manuskript/manuskript/models/outlineItem.py", line 37, in __init__
    abstractItem.__init__(self, model, title, _type, xml, parent, ID)
  File "/app/lib/manuskript/manuskript/models/abstractItem.py", line 45, in __init__
    self.setFromXML(xml)
  File "/app/lib/manuskript/manuskript/models/abstractItem.py", line 319, in setFromXML
    root = ET.XML(xml)
  File "src/lxml/etree.pyx", line 3216, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 1, column 1039
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/app/lib/manuskript/manuskript/models/abstractModel.py", line 316, in canDropMimeData
    items = self.decodeMimeData(data)
  File "/app/lib/manuskript/manuskript/models/abstractModel.py", line 367, in decodeMimeData
    item = outlineItem(xml=ET.tostring(child))
  File "/app/lib/manuskript/manuskript/models/outlineItem.py", line 37, in __init__
    abstractItem.__init__(self, model, title, _type, xml, parent, ID)
  File "/app/lib/manuskript/manuskript/models/abstractItem.py", line 45, in __init__
    self.setFromXML(xml)
  File "/app/lib/manuskript/manuskript/models/abstractItem.py", line 319, in setFromXML
    root = ET.XML(xml)
  File "src/lxml/etree.pyx", line 3216, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 1, column 1039

**Comment by obw** [comment]
Thanks, I hope it helps to find the Bug!
