### ISSUE TITLE
Software crashing every time I open

### ISSUE THREAD

**Issue by mcgratta144** [olivierkes/manuskript#1247]
Issue: Opening it causes it to crash after 2 seconds. It doesn't give me a chance to work on it.
Version: 0.16.0 Windows
Operating System: Windows 10

**Comment by TheShadowOfHassen** [comment]
can you get a log?

**Comment by TheJackiMonster** [comment]
I assume it crashes on your project when trying to open it on startup. But without log or debug output, there's little to be sure. You could try to open Manuskript from a command line interface or look for the log file.

**Comment by mcgratta144** [comment]
2023-12-10 21:28:28,106 - manuskript.load_save.version_1 - DEBUG - Strange things in file
2023-12-10 21:28:48,613 - manuskript.load_save.version_1 - DEBUG - Unknown type: folder
2023-12-10 21:28:49,603 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript\mainWindow.py", line 1206, in saveDatas
  File "manuskript\loadSave.py", line 23, in saveProject
  File "manuskript\load_save\version_1.py", line 358, in saveProject

**Comment by TheShadowOfHassen** [comment]
Try deleting the file found at USERNAME/Software/manuskript/manuskript

**Comment by mcgratta144** [comment]
Where do I find that?

**Comment by TheShadowOfHassen** [comment]
USERNAME should be your username.

**Comment by TheJackiMonster** [comment]
I'm not sure how this issue never occured in previous versions but I have implemented a patch now. Once the pipeline is done, you can try the build from here: https://github.com/olivierkes/manuskript/actions/runs/7183624913

The issue seems to be that a project path was potentially inconsistent on Windows mixing forward slashes and backward slashes as path separators.
