### ISSUE TITLE
UnicodeEncodeError in v0.16.1

### ISSUE THREAD

**Issue by AndrewDemidov** [olivierkes/manuskript#1293]
Attempting to launch the CLI version fails with the following:
--------
Logging to STDERR.
An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript.py", line 13, in <module>
  File "manuskript\main.py", line 308, in run
  File "manuskript\main.py", line 38, in prepare
  File "manuskript\logging.py", line 119, in logToFile
  File "manuskript\logging.py", line 105, in formatLogName
--------
It should obviously succeed instead.
--------

**Comment by TheJackiMonster** [comment]
Wasn't able to reproduce.
