### ISSUE TITLE
Crash By Clicking Outline

### ISSUE THREAD

**Issue by djsmith4570** [olivierkes/manuskript#1299]
[2024-06-06_16-44-46_manuskript#7612.log](https://github.com/user-attachments/files/15686817/2024-06-06_16-44-46_manuskript.7612.log)

I set my qt theme to fusion after reading a previous issue from back in 2019. It still crashes every time I click on the outline section regardless of themes. I'm assuming there's something else going on here. I've tried nothin and I'm all outta ideas.

**Comment by djsmith4570** [comment]
2024-06-06 16:44:46,097 - manuskript.logging - INFO - Logging to file: /home/smith-d/.local/share/manuskript/manuskript/logs/2024-06-06_16-44-46_manuskript#7612.log
2024-06-06 16:44:46,107 - manuskript - INFO - Operating System: Linux-5.15.0-112-generic-x86_64-with-glibc2.35
2024-06-06 16:44:46,108 - manuskript - INFO - Hardware: x86_64 / x86_64
2024-06-06 16:44:46,108 - manuskript - INFO - Running from unpackaged source code.
2024-06-06 16:44:46,108 - manuskript - DEBUG - * sys.executable = '/usr/bin/python3'
2024-06-06 16:44:46,109 - manuskript - DEBUG - * sys.argv = ['/usr/bin/manuskript']
2024-06-06 16:44:46,109 - manuskript - DEBUG - * sys.path = ['/usr/bin',
 '/usr/share/manuskript/',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.10/dist-packages']
2024-06-06 16:44:46,110 - manuskript - DEBUG - * sys.prefix = '/usr'
2024-06-06 16:44:46,113 - manuskript - INFO - Manuskript 0.12.0 (Python 3.10.12)
2024-06-06 16:44:46,113 - manuskript - INFO - * PyQt 5.15.6 (compiled against Qt 5.15.3)
2024-06-06 16:44:46,113 - manuskript - INFO -   * Qt 5.15.3 (runtime)
2024-06-06 16:44:46,137 - manuskript - INFO - * lxml.etree 4.8.0.0
2024-06-06 16:44:46,137 - manuskript - INFO -   * libxml   2.9.13 (compiled: 2.9.13)
2024-06-06 16:44:46,137 - manuskript - INFO -   * libxslt  1.1.34 (compiled: 1.1.34)
2024-06-06 16:44:46,137 - manuskript - INFO - * pyEnchant 3.2.0 (libenchant: 2.3.2)
2024-06-06 16:44:46,138 - manuskript - INFO - * pySpellChecker N/A
2024-06-06 16:44:46,139 - manuskript - INFO - * Symspellpy N/A
2024-06-06 16:44:46,296 - manuskript - INFO - * Markdown 3.3.6
2024-06-06 16:44:46,298 - manuskript - INFO - Web rendering engine: QtWebKit
2024-06-06 16:44:46,328 - manuskript.main - INFO - Preferred translation: ['en-US'] (based on available ui languages)
2024-06-06 16:44:46,328 - manuskript.main - INFO - Using the builtin translation. (U.S. English)
2024-06-06 16:44:47,167 - manuskript.loadSave - INFO - Loading: /home/smith-d/Documents/Writing Stuff/Earl Cross Adventures.msk
2024-06-06 16:44:47,167 - manuskript.loadSave - INFO - Detected file format version: 1. Zip: True.
2024-06-06 16:44:47,168 - manuskript.load_save.version_1 - DEBUG - Loading /home/smith-d/Documents/Writing Stuff/Earl Cross Adventures.msk (zip)
2024-06-06 16:44:47,188 - manuskript.load_save.version_1 - DEBUG - Reading labels:
2024-06-06 16:44:47,189 - manuskript.load_save.version_1 - DEBUG - * Add status: Idea (#ffff00)
2024-06-06 16:44:47,189 - manuskript.load_save.version_1 - DEBUG - * Add status: Note (#00ff00)
2024-06-06 16:44:47,189 - manuskript.load_save.version_1 - DEBUG - * Add status: Chapter (#0000ff)
2024-06-06 16:44:47,189 - manuskript.load_save.version_1 - DEBUG - * Add status: Scene (#ff0000)
2024-06-06 16:44:47,189 - manuskript.load_save.version_1 - DEBUG - * Add status: Research (#00ffff)
2024-06-06 16:44:47,190 - manuskript.load_save.version_1 - DEBUG - Reading status:
2024-06-06 16:44:47,190 - manuskript.load_save.version_1 - DEBUG - * Add status: TODO
2024-06-06 16:44:47,190 - manuskript.load_save.version_1 - DEBUG - * Add status: First draft
2024-06-06 16:44:47,190 - manuskript.load_save.version_1 - DEBUG - * Add status: Second draft
2024-06-06 16:44:47,190 - manuskript.load_save.version_1 - DEBUG - * Add status: Final
2024-06-06 16:44:47,191 - manuskript.load_save.version_1 - DEBUG - Reading plots:
2024-06-06 16:44:47,192 - manuskript.load_save.version_1 - DEBUG - * Add plot: New Plot
2024-06-06 16:44:47,192 - manuskript.load_save.version_1 - DEBUG - Reading World:
2024-06-06 16:44:47,193 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Physical
2024-06-06 16:44:47,193 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Climate
2024-06-06 16:44:47,193 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Topography
2024-06-06 16:44:47,193 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Astronomy
2024-06-06 16:44:47,194 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Natural resources
2024-06-06 16:44:47,194 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Wild life
2024-06-06 16:44:47,194 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Flora
2024-06-06 16:44:47,194 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: History
2024-06-06 16:44:47,195 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Races
2024-06-06 16:44:47,195 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Diseases
2024-06-06 16:44:47,195 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Cultural
2024-06-06 16:44:47,195 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Customs
2024-06-06 16:44:47,196 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Food
2024-06-06 16:44:47,196 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Languages
2024-06-06 16:44:47,196 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Education
2024-06-06 16:44:47,197 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Dresses
2024-06-06 16:44:47,197 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Science
2024-06-06 16:44:47,197 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Calendar
2024-06-06 16:44:47,197 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Bodily language
2024-06-06 16:44:47,197 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Ethics
2024-06-06 16:44:47,198 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Religion
2024-06-06 16:44:47,198 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Government
2024-06-06 16:44:47,198 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Politics
2024-06-06 16:44:47,198 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Gender roles
2024-06-06 16:44:47,199 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Music and arts
2024-06-06 16:44:47,199 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Architecture
2024-06-06 16:44:47,199 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Military
2024-06-06 16:44:47,199 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Technology
2024-06-06 16:44:47,200 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Courtship
2024-06-06 16:44:47,200 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Demography
2024-06-06 16:44:47,200 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Transportation
2024-06-06 16:44:47,200 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Medicine
2024-06-06 16:44:47,201 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Magic system
2024-06-06 16:44:47,201 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Rules
2024-06-06 16:44:47,201 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Organization
2024-06-06 16:44:47,201 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Magical objects
2024-06-06 16:44:47,202 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Magical places
2024-06-06 16:44:47,202 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Magical races
2024-06-06 16:44:47,202 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Important places
2024-06-06 16:44:47,202 - manuskript.load_save.version_1 - DEBUG - * Add worldItem: Important objects
2024-06-06 16:44:47,202 - manuskript.load_save.version_1 - DEBUG - Reading Characters:
2024-06-06 16:44:47,203 - manuskript.load_save.version_1 - DEBUG - Reading outline:
2024-06-06 16:44:47,205 - manuskript.load_save.version_1 - DEBUG - * Adds 00-Chapter_1 to Root (folder)
2024-06-06 16:44:47,206 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 1 (file)
2024-06-06 16:44:47,209 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 1 (file)
2024-06-06 16:44:47,212 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 1 (file)
2024-06-06 16:44:47,215 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 1 (file)
2024-06-06 16:44:47,217 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 1 (file)
2024-06-06 16:44:47,221 - manuskript.load_save.version_1 - DEBUG - * Adds 01-Chapter_2 to Root (folder)
2024-06-06 16:44:47,221 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 2 (file)
2024-06-06 16:44:47,224 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 2 (file)
2024-06-06 16:44:47,227 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 2 (file)
2024-06-06 16:44:47,230 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 2 (file)
2024-06-06 16:44:47,233 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 2 (file)
2024-06-06 16:44:47,236 - manuskript.load_save.version_1 - DEBUG - * Adds 02-Chapter_3 to Root (folder)
2024-06-06 16:44:47,236 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 3 (file)
2024-06-06 16:44:47,239 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 3 (file)
2024-06-06 16:44:47,242 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 3 (file)
2024-06-06 16:44:47,245 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 3 (file)
2024-06-06 16:44:47,248 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 3 (file)
2024-06-06 16:44:47,251 - manuskript.load_save.version_1 - DEBUG - * Adds 03-Chapter_4 to Root (folder)
2024-06-06 16:44:47,251 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 4 (file)
2024-06-06 16:44:47,254 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 4 (file)
2024-06-06 16:44:47,257 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 4 (file)
2024-06-06 16:44:47,260 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 4 (file)
2024-06-06 16:44:47,263 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 4 (file)
2024-06-06 16:44:47,266 - manuskript.load_save.version_1 - DEBUG - * Adds 04-Chapter_5 to Root (folder)
2024-06-06 16:44:47,267 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 5 (file)
2024-06-06 16:44:47,270 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 5 (file)
2024-06-06 16:44:47,273 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 5 (file)
2024-06-06 16:44:47,276 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 5 (file)
2024-06-06 16:44:47,279 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 5 (file)
2024-06-06 16:44:47,282 - manuskript.load_save.version_1 - DEBUG - * Adds 05-Chapter_6 to Root (folder)
2024-06-06 16:44:47,283 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 6 (file)
2024-06-06 16:44:47,286 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 6 (file)
2024-06-06 16:44:47,289 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 6 (file)
2024-06-06 16:44:47,292 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 6 (file)
2024-06-06 16:44:47,295 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 6 (file)
2024-06-06 16:44:47,298 - manuskript.load_save.version_1 - DEBUG - * Adds 06-Chapter_7 to Root (folder)
2024-06-06 16:44:47,299 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 7 (file)
2024-06-06 16:44:47,302 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 7 (file)
2024-06-06 16:44:47,305 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 7 (file)
2024-06-06 16:44:47,308 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 7 (file)
2024-06-06 16:44:47,311 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 7 (file)
2024-06-06 16:44:47,314 - manuskript.load_save.version_1 - DEBUG - * Adds 07-Chapter_8 to Root (folder)
2024-06-06 16:44:47,315 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 8 (file)
2024-06-06 16:44:47,318 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 8 (file)
2024-06-06 16:44:47,321 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 8 (file)
2024-06-06 16:44:47,324 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 8 (file)
2024-06-06 16:44:47,327 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 8 (file)
2024-06-06 16:44:47,330 - manuskript.load_save.version_1 - DEBUG - * Adds 08-Chapter_9 to Root (folder)
2024-06-06 16:44:47,331 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 9 (file)
2024-06-06 16:44:47,334 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 9 (file)
2024-06-06 16:44:47,337 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 9 (file)
2024-06-06 16:44:47,340 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 9 (file)
2024-06-06 16:44:47,343 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 9 (file)
2024-06-06 16:44:47,346 - manuskript.load_save.version_1 - DEBUG - * Adds 09-Chapter_10 to Root (folder)
2024-06-06 16:44:47,347 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 10 (file)
2024-06-06 16:44:47,350 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 10 (file)
2024-06-06 16:44:47,353 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 10 (file)
2024-06-06 16:44:47,356 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 10 (file)
2024-06-06 16:44:47,360 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 10 (file)
2024-06-06 16:44:47,363 - manuskript.load_save.version_1 - DEBUG - * Adds 10-Chapter_11 to Root (folder)
2024-06-06 16:44:47,364 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 11 (file)
2024-06-06 16:44:47,367 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 11 (file)
2024-06-06 16:44:47,370 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 11 (file)
2024-06-06 16:44:47,373 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 11 (file)
2024-06-06 16:44:47,376 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 11 (file)
2024-06-06 16:44:47,380 - manuskript.load_save.version_1 - DEBUG - * Adds 11-Chapter_12 to Root (folder)
2024-06-06 16:44:47,380 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 12 (file)
2024-06-06 16:44:47,384 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 12 (file)
2024-06-06 16:44:47,387 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 12 (file)
2024-06-06 16:44:47,390 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 12 (file)
2024-06-06 16:44:47,393 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 12 (file)
2024-06-06 16:44:47,397 - manuskript.load_save.version_1 - DEBUG - * Adds 12-Chapter_13 to Root (folder)
2024-06-06 16:44:47,397 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 13 (file)
2024-06-06 16:44:47,401 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 13 (file)
2024-06-06 16:44:47,404 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 13 (file)
2024-06-06 16:44:47,407 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 13 (file)
2024-06-06 16:44:47,411 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 13 (file)
2024-06-06 16:44:47,414 - manuskript.load_save.version_1 - DEBUG - * Adds 13-Chapter_14 to Root (folder)
2024-06-06 16:44:47,415 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 14 (file)
2024-06-06 16:44:47,418 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 14 (file)
2024-06-06 16:44:47,421 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 14 (file)
2024-06-06 16:44:47,425 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 14 (file)
2024-06-06 16:44:47,428 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 14 (file)
2024-06-06 16:44:47,432 - manuskript.load_save.version_1 - DEBUG - * Adds 14-Chapter_15 to Root (folder)
2024-06-06 16:44:47,433 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 15 (file)
2024-06-06 16:44:47,436 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 15 (file)
2024-06-06 16:44:47,439 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 15 (file)
2024-06-06 16:44:47,443 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 15 (file)
2024-06-06 16:44:47,446 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 15 (file)
2024-06-06 16:44:47,449 - manuskript.load_save.version_1 - DEBUG - * Adds 15-Chapter_16 to Root (folder)
2024-06-06 16:44:47,450 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 16 (file)
2024-06-06 16:44:47,454 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 16 (file)
2024-06-06 16:44:47,457 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 16 (file)
2024-06-06 16:44:47,461 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 16 (file)
2024-06-06 16:44:47,464 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 16 (file)
2024-06-06 16:44:47,468 - manuskript.load_save.version_1 - DEBUG - * Adds 16-Chapter_17 to Root (folder)
2024-06-06 16:44:47,468 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 17 (file)
2024-06-06 16:44:47,472 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 17 (file)
2024-06-06 16:44:47,475 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 17 (file)
2024-06-06 16:44:47,479 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 17 (file)
2024-06-06 16:44:47,482 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 17 (file)
2024-06-06 16:44:47,486 - manuskript.load_save.version_1 - DEBUG - * Adds 17-Chapter_18 to Root (folder)
2024-06-06 16:44:47,487 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 18 (file)
2024-06-06 16:44:47,490 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 18 (file)
2024-06-06 16:44:47,494 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 18 (file)
2024-06-06 16:44:47,497 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 18 (file)
2024-06-06 16:44:47,501 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 18 (file)
2024-06-06 16:44:47,504 - manuskript.load_save.version_1 - DEBUG - * Adds 18-Chapter_19 to Root (folder)
2024-06-06 16:44:47,505 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 19 (file)
2024-06-06 16:44:47,509 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 19 (file)
2024-06-06 16:44:47,512 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 19 (file)
2024-06-06 16:44:47,516 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 19 (file)
2024-06-06 16:44:47,520 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 19 (file)
2024-06-06 16:44:47,523 - manuskript.load_save.version_1 - DEBUG - * Adds 19-Chapter_20 to Root (folder)
2024-06-06 16:44:47,524 - manuskript.load_save.version_1 - DEBUG - * Adds 0-Scene_1.md to Chapter 20 (file)
2024-06-06 16:44:47,528 - manuskript.load_save.version_1 - DEBUG - * Adds 1-Scene_2.md to Chapter 20 (file)
2024-06-06 16:44:47,531 - manuskript.load_save.version_1 - DEBUG - * Adds 2-Scene_3.md to Chapter 20 (file)
2024-06-06 16:44:47,535 - manuskript.load_save.version_1 - DEBUG - * Adds 3-Scene_4.md to Chapter 20 (file)
2024-06-06 16:44:47,538 - manuskript.load_save.version_1 - DEBUG - * Adds 4-Scene_5.md to Chapter 20 (file)
2024-06-06 16:44:47,544 - manuskript.mainWindow - INFO - Project /home/smith-d/Documents/Writing Stuff/Earl Cross Adventures.msk loaded.
2024-06-06 16:53:25,180 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 32, in paint
    iconRect = style.subElementRect(style.SE_ItemViewItemDecoration, opt)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments

**Comment by TheJackiMonster** [comment]
Can you try whether a newer version of Manuskript fixes that problem? The log states you are using Manuskript 0.12.0.

**Comment by bvanrosendale** [comment]
I'm also seeing this issue on Manuskript 0.16.1 with `Python 3.12.4`, `PyQt 5.15.11`, and `Qt 5.15.14`

```
$ manuskript

(process:37418): libenchant-WARNING **: 18:55:16.982: broker.vala:159: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

(process:37418): libenchant-WARNING **: 18:55:16.982: broker.vala:159: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

(process:37418): libenchant-WARNING **: 18:55:16.982: broker.vala:159: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

(process:37418): libenchant-WARNING **: 18:55:16.982: broker.vala:159: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory
** Message: 18:55:27.960: Connecting to org.freedesktop.Tracker3.Miner.Files

** (org.gnome.Nautilus:37630): WARNING **: 18:55:28.151: Unable to get contents of the bookmarks file: Error opening file /home/brie/.gtk-bookmarks: No such file or directory

** (org.gnome.Nautilus:37630): WARNING **: 18:55:28.151: Unable to create connection for session-wide Tracker indexer: TheCRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 32, in paint
    iconRect = style.subElementRect(style.SE_ItemViewItemDecoration, opt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: subElementRect(self, element: QStyle.SubElement, option: Optional[QStyleOption], widget: Optional[QWidget]): not enough arguments
Fatal Python error: Segmentation fault

Current thread 0x000074cc416b7b80 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 246 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 312 in run
  File "/usr/bin/manuskript", line 30 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtXml, PyQt5.QtX11Extras, PyQt5.QtTest, PyQt5.QtSvg, PyQt5.QtSql, PyQt5.QtPrintSupport, PyQt5.QtOpenGL, PyQt5.QtDBus, PyQt5.QtNetwork, lxml._elementpath, lxml.etree (total: 14)
[1]    37418 segmentation fault (core dumped)  manuskript
```

Log file: [2024-08-10_18-55-17_manuskript#37418.log](https://github.com/user-attachments/files/16571095/2024-08-10_18-55-17_manuskript.37418.log)

I spent a tiny bit of time messing around with themes and stuff, so it _could_ be something weird on my system that's allowing that, but I have no idea.

This is happening on a totally new project with no content at all, and everything on my system is up-to-date.

I might get around to poking at the source code myself, although I'm not sure if I'll spend enough time to get anywhere. I am happy to help debug this further if that's useful.
