### ISSUE TITLE
Manuskript 0.16.1 crashes after a while of being opened

### ISSUE THREAD

**Issue by manito-manopla** [olivierkes/manuskript#1302]
Every time I try to do something in manuskript, usually when I try to write, the program crashes.  Here is the simple output and verbose of the terminal (I put the boxes there intentionally to cover the name of the document).

Simple.
```
Fatal Python error: Segmentation fault
Current thread 0xb7b4fc80 (most recent call first):
File "/usr/share/manuskript/manuskript/main.py", line 246 in launch
File "/usr/share/manuskript/manuskript/main.py", line 312 in run
File "/usr/bin/manuskript", line 30 in <module>
Segment violation
```
Verbose
```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
File "/usr/share/manuskript/manuskript/mainWindow.py", line 1210, in saveDatas
r = loadSave.saveProject()  # version=0
File "/usr/share/manuskript/manuskript/loadSave.py", line 23, in saveProject
return v1.saveProject()
File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 358, in saveProject
os.replace(oldPath, newPath)
OSError: [Errno 36] File name too long: '/home/user/Documents/writer/manuskript/███████████████/outline/0-New.md' 
-> '/home/user/Documents/writer/manuskript/███████████████/outline/0-Fatal_Python_error-
_Segmentation_fault____Current_thread_0xb7b4fc80_-most_recent_call_first--____File_--usr-share-manuskript-manuskript-
main-py--_line_246_in_launch____File_--usr-share-manuskript-manuskript-main-py--_line_312_in_run____File_--usr-bin-
manuskript--_line_30_in_-module-__Violaci-n_de_segmento.md'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 721, in focusOutEvent
self.submit()
File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 330, in submit
self.updateTimer.stop()
RuntimeError: wrapped C/C++ object of type QTimer has been deleted

The above exception was the direct cause of the following exception:

SystemError: _PyEval_EvalFrameDefault returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtGui.QHideEvent'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.9/logging/__init__.py", line 2129, in shutdown
for wr in reversed(handlerList[:]):
SystemError: <built-in method __reversed__ of list object at 0xa3c1f4a8> returned a result with an error set
```

**Comment by TheJackiMonster** [comment]
Okay, so it looks like it's throwing an error in Python ``OSError: [Errno 36] File name too long: [...]`` but the actual name of the file path contains output because of a segmentation fault.

So I assume the problem is not inside the code saving the project but somewhere else and the autosave is just accidentally obfuscating the error log. Weird but possible. ^^'

Technically for the rest it looks like the problem might be inside `manuskript/ui/views/textEditView.py`. Could be finally a segmentation fault that's not caused by some Qt theme.

**Comment by manito-manopla** [comment]
I disabled autosave, but the problem still persists

**Comment by marosoft** [comment]
It might just be the order the code is executed. I will try to reproduce and add the fix.

**Comment by Kalamets** [comment]
So I actually ran into this same issue just recently.  Manuskript would crash when using the Editor feature.  If I was tooling around in menus or other parts it would be fine.  It was only related to the Editor.  This occurred in the most recent distros of Mint (Cinnamon), Debian (Gnome), as well as Pop_OS.  All of them had Manuskript installed using the .deb, and the reason for doing that was because I was having issues getting any of them to give a proper dark mode with the Flatpak.

However, once I switched back to the Flatpak, my issues went away.  At this point I'll take the lack of dark mode if it means no crashing.  So I'm assuming it's some package that's different between the flatpak and whatever the system has updated with the .deb.

**Comment by TheJackiMonster** [comment]
I've commited some fixes upstream. So you could try running Manuskript from source and it should be fixed. Reopen if it still persists.
