### ISSUE TITLE
Manuskript crashes when attempting search

### ISSUE THREAD

**Issue by iww-clydeside** [olivierkes/manuskript#1313]
We have a small (ish) document and a large one. On both Manuskript has crashed whenever I use the search function. I couldn't find an open issue for this, I did try to check.

On debian bookworm.

**Comment by ByteOfBrie** [comment]
Based on the [package list](https://packages.debian.org/bookworm/editors/manuskript), debian bookworm uses Manuskript 0.14

I found #1218, which _could_ be related, since it's fixed in a newer version, but it's hard to tell without logs. If you can attach those, that would be useful. See step three [here](https://github.com/olivierkes/manuskript/wiki/Submitting-an-issue-on-Github)

**Comment by iww-clydeside** [comment]
Running to from source seems to have fixed the issue, woo hoo!



On 12 August 2024 01:28:47 BST, Brie ***@***.***> wrote:
>Based on the [package list](https://packages.debian.org/bookworm/editors/manuskript), debian bookworm uses Manuskript 0.14
>
>I found #1218, which _could_ be related, since it's fixed in a newer version, but it's hard to tell without logs. If you can attach those, that would be useful. See step three [here](https://github.com/olivierkes/manuskript/wiki/Submitting-an-issue-on-Github)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/olivierkes/manuskript/issues/1313#issuecomment-2282949085
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
___________

Malik (they/them)
Industrial Workers of the World (IWW), https://IWW.ORG.UK

This message, including attachments, is confidential • If you have received this message in error, we apologise and would be grateful if you could notify ***@***.*** and delete this message • By corresponding with the IWW through email, you confirm that you have read, understood and accepted our GDPR Privacy Statement• The IWW is a certified independent trade union registered in the United Kingdom; Certification Officer List Number 790T • IWW Wales, Ireland, Scotland & England Regional Administration (WISE-RA), PO Box 111, Minehead, TA24 9DH, United Kingdom.

**Comment by iww-clydeside** [comment]
It is turning up intermittently. Sometimes it works sometimes it doesn't. I can't figure out which log file contains the error so I've attached all of the ones from yesterday.
[2024-08-12_01-12-56_manuskript#3108.log](https://github.com/user-attachments/files/16594734/2024-08-12_01-12-56_manuskript.3108.log)
[2024-08-12_05-56-03_manuskript#3118.log](https://github.com/user-attachments/files/16594735/2024-08-12_05-56-03_manuskript.3118.log)
[2024-08-12_12-07-06_manuskript#39958.log](https://github.com/user-attachments/files/16594736/2024-08-12_12-07-06_manuskript.39958.log)

**Comment by ByteOfBrie** [comment]
Thanks for providing the logs!

The crash happens in the last log file:

```
2024-08-12 17:56:04,641 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/search.py", line 142, in search
    results += model.searchOccurrences(searchRegex, filteredColumns)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/manuskript/manuskript/models/searchableModel.py", line 11, in searchOccurrences
    results += item.searchOccurrences(searchRegex, column)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/manuskript/manuskript/models/plotModel.py", line 322, in searchOccurrences
    results += super().searchOccurrences(searchRegex, column)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/manuskript/manuskript/models/searchableItem.py", line 16, in searchOccurrences
    return [self.wrapSearchOccurrence(column, startPos, endPos, context) for (startPos, endPos, context) in search(searchRegex, self.searchData(column))]
                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/manuskript/manuskript/models/plotModel.py", line 354, in searchData
    return self.getItem(self.rowIndex, column).text()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

And this provides more information on the issue. It's definitely the same issue as before, which was fixed in 1fd8762f5a5010f7697c41d75d1b53656899a707.

Looking at the logs, you're on version 0.15, and the linked fix isn't included before 0.16

If you manage to run Manuskript through source, or get a newer version installed, that should be enough to fix it. The version in debian repositories is old, but the download page for Manuskript has instructions for installing version 0.16.1 on debian: https://www.theologeek.ch/manuskript/download/
