### ISSUE TITLE
Crash when opening file, possibly due to platform incompatibility 

### ISSUE THREAD

**Issue by rquinlivan** [olivierkes/manuskript#1348]
I created a project recently and have been editing it on both MacOS and Linux.  I saved some changes on MacOS and found that I cannot open the file on Linux. Manuskript crashes with the following error:

```
Dec 30 18:10:45 socrates systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Dec 30 18:10:45 socrates gnome-shell[4853]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x7c00017 specified for 0x7c00019.
Dec 30 18:10:46 socrates manuskript.desktop[204514]: CRITICAL> An unhandled exception has occurred!
Dec 30 18:10:46 socrates manuskript.desktop[204514]: Traceback (most recent call last):
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/welcome.py", line 148, in loadRecentFile
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.mw.loadProject(act.data())
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/mainWindow.py", line 621, in loadProject
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.mainEditor.setFolderView(settings.folderView)
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/editors/mainEditor.py", line 369, in setFolderView
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.currentEditor().setFolderView(view)
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/editors/editorWidget.py", line 108, in setFolderView
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.setCurrentModelIndex(self.currentIndex)
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/editors/editorWidget.py", line 312, in setCurrentModelIndex
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.setView()
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/editors/editorWidget.py", line 256, in setView
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     addTitle(item)
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/editors/editorWidget.py", line 181, in addTitle
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     edt = MDEditView(self, html="<h{l}>{t}</h{l}>".format(l=min(itm.level() + 1, 5), t=itm.title()),
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/views/MDEditView.py", line 30, in __init__
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     textEditView.__init__(self, parent, index, html, spellcheck,
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 49, in __init__
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.setAutoResize(autoResize)
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 369, in setAutoResize
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.sizeChange()
Dec 30 18:10:46 socrates manuskript.desktop[204514]:   File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 361, in sizeChange
Dec 30 18:10:46 socrates manuskript.desktop[204514]:     self.setMinimumHeight(docHeight)
Dec 30 18:10:46 socrates manuskript.desktop[204514]: TypeError: setMinimumHeight(self, int): argument 1 has unexpected type 'float'
```

**Comment by TheJackiMonster** [comment]
I assume you run some outdated version of Manuskript. Newer version should have fixed this issue already.
