### ISSUE TITLE
Compile Issue for Pandoc Formats

### ISSUE THREAD

**Issue by linuxtopia** [olivierkes/manuskript#186]
Hello,

I've been using Manuskript on Windows 10. Whenever try to compile document as Pandoc formats then program **shuts down** immediately.

Can not compile document cause of that issue.

_Pandoc version that I use is 1.6.0.2_

**Comment by olivierkes** [comment]
Thanks for reporting.
Just to be sure: you're using a package / binary? You're not running from source?

**Comment by linuxtopia** [comment]
Ahh sorry forgot to mention that. I used always binary versions of Manuskript

**Comment by gedakc** [comment]
So far with Windows 10, manusrkript-0.5.0-win32.zip, and [pandoc-1.19.2.1-windows.msi](https://github.com/jgm/pandoc/releases/1.19.2.1) I have been unable to recreate the crash experienced by @linuxtopia.

It is possible that the crash is related to the content being exported.

Can you try the following?

1. Open your project in manuskript
2. Export to **Plain Text** using Manuskript's built in exporter.  Save file as `myprj-export.txt`
3. Open a command prompt and navigate to the directory containing `myprj-export.txt`
4. Run the command:  `pandoc -s -o myprj-output.html myprj-export.txt`
5. Look for any error messages.  There were none in my testing.
6. Try to open myprj-output.html in a web browser to confirm if the format was converted to HTML.  You might also use `more myprj-output.html` to view the HTML from the command prompt.

**Comment by linuxtopia** [comment]
After Pandoc update there is standart Pandoc.exe in directory but pandoc-citeproc.exe. Then trying to your manner as pandoc-citeproc that command prompts:

```
'pandoc-citeproc' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by gedakc** [comment]
The existence of the **pandoc** executable is critically important so that Manuskript can call out to the external **pandoc** program.

If there is no `pandoc.exe`, would you consider uninstalling pandoc and then installing [pandoc-1.19.2.1-windows.msi](https://github.com/jgm/pandoc/releases/1.19.2.1)?

**Comment by olivierkes** [comment]
> Bingo... It worked now properly :)

Great ! To be sure to understand: pandoc has to be installed separately from manuskript?
@gedakc, wouldn't it be possible to include pandoc.exe in the binary?

> However now Multimarkdown option doesn't work. Whenever click to manage exporters then try to click MultiMarkdown option that Manuskript disappears/shuts down suddenly.

I guess Multimarkdown is not installed on your computer, right?

What I don't understand, is how can you compile if the program is not present? For example MMD is not installed on my computer, and so I cannot compile document with it. What does the "Manage Exporters" window say?

![image](https://user-images.githubusercontent.com/1192933/32352509-c5f77afc-c021-11e7-84d2-ffc18cb39657.png)

Also, when it crashes, is there any output in console?

**Comment by gedakc** [comment]
> wouldn't it be possible to include pandoc.exe in the binary?

It is likely possible, but should not be necessary.  Manuskript should behave the same whether run from source code or from the PyInstaller package.  We might need to check the pandoc invocation to see if we are properly handling things like return codes.

> Multimarkdown option doesn't work. Whenever click to manage exporters then try to click MultiMarkdown option that Manuskript disappears/shuts down suddenly.

I will look into multimarkdown tomorrow.

**Comment by linuxtopia** [comment]
> Great ! To be sure to understand: pandoc has to be installed separately from manuskript?

Yes it's separately from manuskript.

> I guess Multimarkdown is not installed on your computer, right?

Nope, I had installed it

![everything_2017-11-03_15-39-59](https://user-images.githubusercontent.com/19939134/32374328-39814688-c0ae-11e7-94b4-bcbbd4a1b41e.png)

> What I don't understand, is how can you compile if the program is not present? For example MMD is not installed on my computer, and so I cannot compile document with it.

I had no just Latex so PDF option not work as duly but I don't understand too why Multimarkdown doesn't work even it's installed.

> What does the "Manage Exporters" window say?

It says nothing whenever I click then it closes itself suddenly like a flash.

![2017-11-03_15-53-26](https://user-images.githubusercontent.com/19939134/32374533-38866168-c0af-11e7-9bee-9d61e740c865.gif)

**Comment by gedakc** [comment]
To get more information for debugging I ran `manuskript.exe` from a command prompt.  The output is as follows:

```
C:\manuskript-0.5.0-win32>manuskript.exe
Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_US.
Loading: C:/Users/gedak/Documents/deleteme-manuskript.msk
Detected file format version: 1. Zip: True.
Project C:/Users/gedak/Documents/deleteme-manuskript.msk loaded.
Traceback (most recent call last):
  File "manuskript\ui\exporters\exportersManager.py", line 98, in updateUi
  File "manuskript\exporter\mmd.py", line 24, in version
  File "manuskript\exporter\basic.py", line 61, in run
  File "subprocess.py", line 620, in check_output
subprocess.CalledProcessError: Command '['multimarkdown', '-v']' returned non-zero exit status 1

C:\manuskript-0.5.0-win32>
```

In addition I ran `multimarkdown` directly.

```
C:\manuskript-0.5.0-win32>multimarkdown -v
MultiMarkdown: invalid option "-v"
Try 'multimarkdown --help' for more information.

C:\manuskript-0.5.0-win32>
```

It looks like we have an invalid **-v** option for `multimarkdown`.  Following is output from **--help** option.

```
C:\manuskript-0.5.0-win32>multimarkdown --help

MultiMarkdown v6.2.2 -- Copyright -¬ 2016 - 2017 Fletcher T. Penney.

        Usage: multimarkdown [-bfscarm] [--help] [--version] [--random] [--nosmart] [--nolabels] [--notransclude] [-t FORMAT] [-o FILE] [-l LANG] [-e KEY] [<FILE>]...

Options:
        --help                    display this help and exit
        --version                 display version info and exit

        -b, --batch               process each file separately
        -f, --full                force a complete document
        -s, --snippet             force a snippet
        -c, --compatibility       Markdown compatibility mode
        --random                  use random numbers for footnote anchors
        --nosmart                 Disable smart typography
        --nolabels                Disable id attributes for headers
        --notransclude            Disable file transclusion

        -t, --to=FORMAT           convert to FORMAT, FORMAT = html|latex|beamer|memoir|mmd|odt|fodt|epub|bundle|bundlezip
        -o, --output=FILE         send output to FILE

        -a, --accept              accept all CriticMarkup changes
        -r, --reject              reject all CriticMarkup changes

        -l, --lang=LANG           language/smart quote localization, LANG = en|es|de|fr|he|nl|sv

        -m, --metadata-keys       list all metadata keys
        -e, --extract=KEY         extract specified metadata key

        <FILE>                    read input from file(s) -- use stdin if no files given


C:\manuskript-0.5.0-win32>
```

Based on the output I think we have an issue with how we invoke commands and handle return codes.

**Comment by olivierkes** [comment]
>It is likely possible, but should not be necessary. Manuskript should behave the same whether run from source code or from the PyInstaller package. [about packaging pandoc in the pyInstaller package]

From a user standpoint, I guess they want out of the box the ability to export. So why not avoid them the supplementary step of downloading and installing a second software?

>subprocess.CalledProcessError: Command '['multimarkdown', '-v']' returned non-zero exit status 1

It's clear that there is an error here that needs to be handled. And MMD has to be called with `--version` instead of `-v` (maybe I had an older version when I tried?)

Anyhow, that would explain the crash in the "Manage Exporters" window, when clicking on MultiMarkDown. But that doesn't explain the first crash (in the original post), when pandoc was not installed. @gedakc, you've not been able to reproduce this one, right?

> @olivierkes do I need to install any python modules to support MultiMarkDown?

No, manuskript calls directly MMD without using a python package. It's just that I haven't written the proper exporter, I think.

But my question now is: **is it really necessary to use MMD?** If I remember correctly I came upon it first (when I decided to abandon txt2tags in favor of markdown). And later only did I see pandoc. pandoc can do everything that MMD can do, and more.

**Comment by gedakc** [comment]
Thank you @linuxtopia and @olivierkes for your input on this issue.

> From a user standpoint, I guess they want out of the box the ability to export. So why not avoid them the supplementary step of downloading and installing a second software?

That's a good question.  There are a few reasons I can think of why we *should not* bundle pandoc with the manuskript PyInstaller package:

1. Manuskript should not crash regardless of whether pandoc is installed or not.  We probably have a bug in our code.
2. We do not wish to take on added packaging responsibility.  If a security bug is found in pandoc and we included pandoc in our package, then we _should_ update our package _every time_ a pandoc bug is fixed.
3. Pandoc may be used with other programs outside of manuskript.  Multiple copies of pandoc should not be required for each and every program that uses pandoc.
4. The user should have the freedom to install (or not install) a specific version of pandoc if they so wish.
5. When we eventually have OS specific install packages these should not include a copy of pandoc.  For example in Debian and Ubuntu, packages can require or suggest other packages, but never actually include a separate copy of the package.

> But that doesn't explain the first crash (in the original post), when pandoc was not installed. @gedakc, you've not been able to reproduce this one, right?

Now that I have a better understanding of the issue I will try some more things in an effort to reproduce the problem.

> Is it really necessary to use MMD?  Pandoc can do everything that MMD can do, and more.

If pandoc can do everything that MMD can do and more, then I think we should consider removing MMD.  This will lighten the effort of maintaining manuskript.  :-)

**Comment by gedakc** [comment]
To reproduce the problem I uninstalled **pandoc** and created a simple `pandoc.bat` file in the folder containing `manuskript.exe`.

pandoc.bat contents:
```
exit 3
```

Now when I open a project in pandoc, select **Compile**, choose pandoc format **HTML**, and click **Preview** then manuskript disappears/crashes.  The output in the console is as follows:

```
C:\manuskript-0.5.0-win32>manuskript.exe
Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_US.
Loading: C:/Users/gedak/Documents/deleteme-manuskript.msk
Detected file format version: 1. Zip: True.
Project C:/Users/gedak/Documents/deleteme-manuskript.msk loaded.
Traceback (most recent call last):
  File "manuskript\ui\exporters\exporter.py", line 90, in preview
  File "manuskript\exporter\pandoc\HTML.py", line 35, in preview
  File "manuskript\exporter\pandoc\abstractPlainText.py", line 32, in output
  File "manuskript\exporter\pandoc\__init__.py", line 74, in convert
  File "subprocess.py", line 859, in __init__
  File "subprocess.py", line 1114, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\manuskript-0.5.0-win32>
```

Note that I do see the list of pandoc export options enabling me to select **HTML** as a format.

**Comment by gedakc** [comment]
I can reproduce a similar issue on GNU/Linux by uninstalling pandoc and creating a `pandoc` file in the PATH with the same `exit 3` contents.

When I open a project in pandoc, select **Compile**, choose pandoc format **HTML**, and click **Preview** then I see the following output in the console window:

```
$ manuskript
Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_CA.
Loading: /home/gedakc/tmp/deleteme-1.msk
Detected file format version: 1. Zip: False.
Project /home/gedakc/tmp/deleteme-1.msk loaded.
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/ui/exporters/exporter.py", line 90, in preview
    F.preview(self.settingsWidget, self.previewWidget)
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/exporter/pandoc/HTML.py", line 35, in preview
    html = self.output(settingsWidget)
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/exporter/pandoc/abstractPlainText.py", line 32, in output
    return self.exporter.convert(src, args, outputfile)
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/exporter/pandoc/__init__.py", line 74, in convert
    stderr=subprocess.PIPE
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
$
```

**Comment by gedakc** [comment]
> Pandoc version that I use is 1.6.0.2( After submission I've updated Pandoc to 2.0.1, still issue is there)

I was unable to locate pandoc 1.6.0.2.  The nearest version I could find was [pandoc 1.6](https://github.com/jgm/pandoc/releases?after=1.8.0.3).

@linuxtopia can you check on the pandoc version number you were originally using?

**Comment by linuxtopia** [comment]
Sorry for misspelling. It was pandoc 1.16.0.2 version and never worked for any version of Manuskript.

![explorer_2017-11-03_21-26-30](https://user-images.githubusercontent.com/19939134/32389985-b0376bca-c0dd-11e7-92c1-589fc553a21c.png)

I hope to supply any kind of collaboration you cause I really loved Manukript after Quoll, Bibisco and Scrivener trials. Manu is most simple and effective one even for it's non stable devoloping cycle. However that issue had made me crazy until today it's solved.

Thanks for your all help ;)

**Comment by gedakc** [comment]
Thank you @linuxtopia for the clarification on the version number.

I installed `pandoc-1.16.0.2-windows.msi` and reran my test steps.  Unfortunately I was unable to recreate the issue you encountered, as pandoc created the appropriate format (no manuskript disappearance or crash).

I did notice that `pandoc -v` is a valid command with pandoc version 1.16.0.2.  The other form `pandoc --version` also works, so we might wish to change our pandoc test to use **--version** option instead of **-v**.

I will continue to investigate how we might improved the robustness of manuskript when it executes external programs like **pandoc**.

**Comment by gedakc** [comment]
I found the cause of the crash when **MultiMarkDown** is not installed and a person selects **Compile**, **Manage exporters**, and clicks on **MultiMarkDown**.

Following is the fix required:

```
diff --git a/manuskript/exporter/mmd.py b/manuskript/exporter/mmd.py
index fbe5bae..4d5e70f 100644
--- a/manuskript/exporter/mmd.py
+++ b/manuskript/exporter/mmd.py
@@ -22,7 +22,7 @@ class mmdExporter(basicExporter):
     def version(self):
         if self.isValid():
             r = self.run(["-v"])
-            return r.split("\n")[1]
+            return r.split("\n")[0]
         else:
             return ""
```

@olivierkes would you prefer to remove MultiMarkDown?

If so then I won't bother pushing a patch to fix the MMD crash issue when MMD is not installed.

**Comment by olivierkes** [comment]
I've created a `feature/Exporters` branch to work on this.
And yes, I removed MMD.

**Comment by olivierkes** [comment]
> we might wish to change our pandoc test to use **--version** option instead of **-v**.

Done.

> My hypothesis is that we have a disconnect with how we detect if pandoc is installed and how we actually use pandoc to convert data from one format to another. Next I will look at how we determine if pandoc is indeed installed.

To give you an headstart: in an exporter, `isValid()` determines whether the command is available:

https://github.com/olivierkes/manuskript/blob/4ddb95ff678769540f29ba4b3385559d85af7d11/manuskript/exporter/basic.py#L39-L45

`self.path()` uses `shutil.which()`:

https://github.com/olivierkes/manuskript/blob/4ddb95ff678769540f29ba4b3385559d85af7d11/manuskript/exporter/basic.py#L50-L51

So if something is found, it is assumed to be the correct program. 

And then, you're right, we use two different functions to run the program:

1. **To determine the version number**

    https://github.com/olivierkes/manuskript/blob/4ddb95ff678769540f29ba4b3385559d85af7d11/manuskript/exporter/basic.py#L53

    It uses [`subprocess.check_output`](https://docs.python.org/3/library/subprocess.html#subprocess.check_output).

2. **To do the actual conversion**

    https://github.com/olivierkes/manuskript/blob/4ddb95ff678769540f29ba4b3385559d85af7d11/manuskript/exporter/pandoc/__init__.py#L48

    It uses [`subprocess.Popen`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen)

So we need to catch [`subprocess`'s exceptions](https://docs.python.org/3/library/subprocess.html#exceptions). (`OSError` and `CalledProcessError`, both we encoutered and reported in this issue, are described there).

**Comment by gedakc** [comment]
Thank you @olivierkes for your detailed response.  Now that you have removed MMD, I can focus on improving the robustness of pandoc using your tips and the _feature/Exporters_ branch.

**Comment by olivierkes** [comment]
I closed the branch `feature/Exporters` because it wasn't really necessary, we can do tests in develop.
And I didn't want to wait to long before merging those changes.

**Comment by gedakc** [comment]
Good choice.  I've been busy with packaging so this had fallen off my radar.

On the plus side manuskript will still run if `pandoc` is correctly installed, which should be the case in most all installations.  Obviously this issue indicates there was at least one instance in which this was not the case.
