### ISSUE TITLE
Program Crash on Import with images

### ISSUE THREAD

**Issue by darrelwright** [olivierkes/manuskript#213]
I realize this feature is not implemented yet (?), but I tried to import a folder that only contained a .png file. I changed line containing *.txt, *.md to read *.txt, *.md, *.png, then clicked "Chose file" and selected the folder, then clicked on "Choose" and immediately Manuskript was killed. Should have given an error message of some kind and refused the operation, correct?

**Comment by olivierkes** [comment]
Thanks for reporting, you're right indeed !

Here is the error message (it's useful for future references if you can do that as well, it can help):

```python
Traceback (most recent call last):
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/manuskript/bin/../manuskript/ui/importers/importer.py", line 239, in preview
    result = self.startImport(previewModel)
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/manuskript/bin/../manuskript/ui/importers/importer.py", line 297, in startImport
    self.settingsWidget)
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/manuskript/bin/../manuskript/importer/folderImporter.py", line 81, in startImport
    addFile(f)
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/manuskript/bin/../manuskript/importer/folderImporter.py", line 48, in addFile
    child._data[Outline.text] = fr.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Fatal Python error: Aborted

Current thread 0x00007f19b1e1a700 (most recent call first):
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/manuskript/bin/../manuskript/main.py", line 76 in launch
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/manuskript/bin/../manuskript/main.py", line 64 in run
  File "bin/manuskript", line 13 in <module>
makefile:10 : la recette pour la cible « run » a échouée
make: *** [run] Abandon (core dump créé)
```

It's been fixed in last commit.
