### ISSUE TITLE
Can't create new project on Linux

### ISSUE THREAD

**Issue by UBy** [olivierkes/manuskript#30]
I get the following error when creating a project on Linux:

Traceback (most recent call last):
  File "/home/DATA/opt/manuskript/bin/../manuskript/ui/welcome.py", line 159, in createFile
    self.loadDefaultDatas()
  File "/home/DATA/opt/manuskript/bin/../manuskript/ui/welcome.py", line 344, in loadDefaultDatas
    t = [i for i in self.templates() if i[0] == self.template[0]]
  File "/home/DATA/opt/manuskript/bin/../manuskript/ui/welcome.py", line 344, in <listcomp>
    t = [i for i in self.templates() if i[0] == self.template[0]]
IndexError: list index out of range

I have no problem opening and saving the example project.

**Comment by olivierkes** [comment]
What version are you running?

**Comment by UBy** [comment]
I was using manuskript-0.3.0-linux-1.zip but also tried the master branch.

Just noticed the instructions about using dev branch (1 minute from writing this) that solved the problem.
