### ISSUE TITLE
Deleting multiple World items leaves/creates two empty items

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#306]
# Problem

When a range of World items are selected and then deleted, two empty items remain after the operation.

This issue does not occur with the official 0.6.0 release, but does occur with with the **develop** branch (most recent commit 8a9044b4ae).  I suspect that the issue may have been introduced when I committed PR #298.

# Steps to Reproduce

Start with a Manuskript project with no World items.

1. Select **World**.

2. Click on *heart* icon at bottom of World items pane and choose **Fantasy World Building**.  This should create many World items.

   ![world-1](https://user-images.githubusercontent.com/10405019/35011927-27f95ada-fac5-11e7-9f2a-e394832db43d.png)

3. Click on top item **Physical**, scroll to bottom and Shift+Click on last item **Important Objects**.  At this point all items should be selected.

4. Click on *minus sign* icon at bottom of World items to delete the selected range.

5. Notice the following:

   - Extra two empty World items:

     ![world-2](https://user-images.githubusercontent.com/10405019/35011949-3733592e-fac5-11e7-9f8b-3b0d15932a87.png)

   - Console message output:
     ```
     $ manuskript
     Debug: Web rendering engine used: QWebView
     Running manuskript version 0.6.0.
     Note: No translator found or loaded for locale en_CA.
     Loading: /home/gedakc/tmp/deleteme-1.msk
     Detected file format version: 1. Zip: False.
     Project /home/gedakc/tmp/deleteme-1.msk loaded.
     Traceback (most recent call last):
       File "/home/gedakc/workspace/manuskript/bin/../manuskript/ui/cheatSheet.py", line 117, in populate
         d = self.worldModel.listAll()
       File "/home/gedakc/workspace/manuskript/bin/../manuskript/models/worldModel.py", line 94, in listAll
         readAll(self.invisibleRootItem())
       File "/home/gedakc/workspace/manuskript/bin/../manuskript/models/worldModel.py", line 92, in readAll
         readAll(c)
       File "/home/gedakc/workspace/manuskript/bin/../manuskript/models/worldModel.py", line 86, in readAll
         name = item.text()
     AttributeError: 'NoneType' object has no attribute 'text'
     Project deleteme-1.msk saved.
     ```

   - Contents of `world.opml` file:
     ```
     <?xml version='1.0' encoding='UTF-8'?>
     <opml version="1.0">
       <body>
         <outline/>
         <outline/>
       </body>
     </opml>
     ```

**Comment by gedakc** [comment]
Thanks to the work of @JackXVII this bug has been fixed.  This enhancement will be included in the next release of Manuskript.
