### ISSUE TITLE
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#31]
```
Traceback (most recent call last):
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/mainWindow.py", line 474, in saveDatas
    loadSave.saveProject()  # version=0
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/loadSave.py", line 21, in saveProject
    v1.saveProject()
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/load_save/version_1.py", line 258, in saveProject
    files.append(("revisions.xml", mdl.saveToXML()))
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/models/outlineModel.py", line 406, in saveToXML
    root = ET.XML(self.rootItem.toXML())
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/models/outlineModel.py", line 766, in toXML
    item.append(ET.XML(i.toXML()))
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/models/outlineModel.py", line 752, in toXML
    item.set(attrib.name, str(val))
  File "lxml.etree.pyx", line 746, in lxml.etree._Element.set (src/lxml/lxml.etree.c:42955)
  File "apihelpers.pxi", line 547, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:19025)
  File "apihelpers.pxi", line 1395, in lxml.etree._utf8 (src/lxml/lxml.etree.c:26485)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by gedakc** [comment]
This bug was also identified in issue #562 and has been fixed with pull request #578.
