### ISSUE TITLE
File Load Failure - Corrupted?

### ISSUE THREAD

**Issue by siliconserf** [olivierkes/manuskript#315]
I'm using 0.6.0 in Ubuntu Linux. There are a pair of project files I am working with. After opening each with a separate instance of Manuskript I shut down first one and then the other. Now only one loads nicely. The other fails to load with no symptoms. I launched through the terminal instead of applications and got this debug trace:

Debug: Web rendering engine used: QWebView
Running manuskript version 0.6.0.
Note: No translator found or loaded for locale en_US.
Loading: /home/charles/Documents/Compositions/Fool's Gate .msk
Detected file format version: 1. Zip: True.
Traceback (most recent call last):
  File "/home/charles/manuskript/manuskript/bin/../manuskript/ui/welcome.py", line 127, in loadRecentFile
    self.mw.loadProject(act.data())
  File "/home/charles/manuskript/manuskript/bin/../manuskript/mainWindow.py", line 517, in loadProject
    self.loadDatas(project)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/mainWindow.py", line 742, in loadDatas
    errors = loadSave.loadProject(project)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/loadSave.py", line 66, in loadProject
    v1.loadProject(project, zip=isZip)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/load_save/version_1.py", line 877, in loadProject
    appendRevisions(mdl, root)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/load_save/version_1.py", line 958, in appendRevisions
    appendRevisions(mdl, child)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/load_save/version_1.py", line 958, in appendRevisions
    appendRevisions(mdl, child)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/load_save/version_1.py", line 958, in appendRevisions
    appendRevisions(mdl, child)
  File "/home/charles/manuskript/manuskript/bin/../manuskript/load_save/version_1.py", line 963, in appendRevisions
    ID = root.attrib["ID"]
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:73200)
KeyError: 'ID'

What is it trying to tell me?

**Comment by gedakc** [comment]
The error appears to indicate a problem loading a revision that has no identifier.

It sounds like you had two different manuskript sessions open on the same project at the same time.  This is currently not supported and is likely to lead to problems due to changes to the file data not being reflected in the memory model of a second running instance of manuskript.

Since you mentioned that one of the instances is able to load the file correctly you might try the following to work-around the issue:

1. Open the project in the manuskript session that works.
2. Change the **Edit -> Settings** preference **Save to one single file** to disabled.
   This should force manuskript to save the project in a folder with multiple files.
3. Close manuskript.
4. Open manuskript and load the project again.
5. Change the **Edit -> Settings** preference **Save to one single file** to enabled again.
6. Close manuskript.

Next try to open manuskript (only one session at a time) in both the manuskript's you mentioned.

**Comment by siliconserf** [comment]
Your solution is based on a slightly newer development version - the option you cite doesn't appear in the released version 0.6.0 **Edit->Settings** menu. However, experimenting I was able to track the problem down to the revision section of the project. Wiping out all but the basic outine markers cleared the problem. 

More important, there is a bug here. Manuskript should not have permitted multiple instances to load if it does not support that capability. I don't know if the Linux or Mac versions, can be set to do that, but it can be done in Windows. 

The whole problem came about because I wanted to copy some "boiler plate" folders and documents I had created, from one project to another. The receiving project was corrupted because it saved revision, while the source project saw no change to its file. I'll work around that in the future.

Thanks.

**Comment by gedakc** [comment]
> ... the option you cite doesn't appear in the released version 0.6.0 **Edit->Settings** menu.

The **Save to one single file** preference is included in version 0.6.0 of Manuskript.  It can be accessed using the **Edit -> Settings** menu and is a *General setting* contained under the *Saving* title.

![screenshot_20180212_133455](https://user-images.githubusercontent.com/10405019/36118265-a551ca50-0ff9-11e8-986d-9932cecfbd28.png)

See also the news article where it was announced on March, 31, 2016:  [Open and plain-text file format](http://www.theologeek.ch/manuskript/2016/03/31/open-plain-text-file-format/)

> Manuskript should not have permitted multiple instances to load if it does not support that capability.

Agreed.  This is mentioned on the [Roadmap](https://github.com/olivierkes/manuskript/wiki/Roadmap) page in the wiki as:
* Collaborative editing: file locks, read-only, (un)shared settings

If you wish this issue to be about preventing multiple instances of manuskript from running, then please feel free to edit the title of the issue accordingly.

**Comment by siliconserf** [comment]
OK, I changed the title and drilling down through General, found the save to single file option. So, eventually that bug will be fixed and the symptom of a corrupted Revision history section/file is a known thing.

Thanks.
