### ISSUE TITLE
Old bugs in current version 0.6.0 (with crosslinks and details)

### ISSUE THREAD

**Issue by BsNoSi** [olivierkes/manuskript#371]
Hi!

I found "Manuskript" accidentally today and was very exited about it. The feature list reads very interesting. Therefore I downloaded the current version 0.6.0 as Windows binary. I tested on a Windows 10x64 Laptip with 8G memory.

The first impressions were very nice. *But* the stability is still (as said on download page) quite poor.

In several situations the program quits without recognizable reason. Some are known:

- Crossing a reference [#275]. 

```
Traceback (most recent call last):
  File "manuskript\ui\views\textEditCompleter.py", line 127, in mouseMoveEvent
  File "manuskript\models\references.py", line 496, in tooltip
ValueError: expected '}' before end of string
```

- Random shutdown [#184] without (recognizable) data loss. (currently no logs because this require description what was done → careful interaction)

- The Pandoc Issue [#186] still exists. It depends on the text if Manuskript shuts down (see below) or simply does nothing. The sample project ends up always with a shutdown.

```
Projekt D:\Downloads\manuskript-0.6.0-win32\manuskript\sample-projects/book-of-acts.msk geladen.
Traceback (most recent call last):
  File "manuskript\ui\exporters\exporter.py", line 101, in preview
  File "manuskript\exporter\pandoc\PDF.py", line 49, in preview
  File "manuskript\exporter\pandoc\PDF.py", line 40, in output
  File "manuskript\exporter\pandoc\__init__.py", line 88, in convert
  File "c:\python34\lib\encodings\cp850.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2721' in position 39: character maps to <undefined>
```

I'd like to investigate more but at the moment I have to go ahead with some other things. I have (for the time being) rejected the idea of using Manuskript for an upcoming documentation. But possibly I can try a little more and give additional feedback.

In general, Manuskript impresses me deeply and I hope that these main issues (because they are the reason making Manuskript not trustworthy for a project) can be fixed soon.

**Comment by gedakc** [comment]
Thank you for your interest in Manuskript.

It would help immensely if you could describe the steps you took that lead to each of the issues you outlined.  Otherwise without a reproducibly case it is very difficult to isolate the cause of many issues.
