### ISSUE TITLE
Application crashes when trying to save "…"

### ISSUE THREAD

**Issue by martin-damien** [olivierkes/manuskript#461]
When the application try to save what I wrote, it crashes if I added the "…" character.

```
Traceback (most recent call last):
  File "manuskript/mainWindow.py", line 765, in saveDatas
  File "manuskript/loadSave.py", line 21, in saveProject
  File "manuskript/load_save/version_1.py", line 260, in saveProject
  File "manuskript/models/abstractModel.py", line 525, in saveToXML
  File "manuskript/models/abstractItem.py", line 275, in toXML
  File "manuskript/models/abstractItem.py", line 275, in toXML
  File "manuskript/models/abstractItem.py", line 266, in toXML
  File "src/lxml/etree.pyx", line 813, in lxml.etree._Element.set
  File "src/lxml/apihelpers.pxi", line 570, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Fatal Python error: Aborted

Current thread 0x00000001108265c0 (most recent call first):
  File "manuskript/main.py", line 89 in launch
  File "manuskript/main.py", line 102 in run
  File "manuskript", line 13 in <module>
[1]    91979 abort      /Users/dmartin/Applications/manuskript/manuskript
```

I use the 0.8.0 version, under MAC OS Mojav.

**Comment by gedakc** [comment]
Where did you add the ellipses (three dots) character?

So far I have been unable to recreate the issue.

From the **Editor** pane I added "…" to a scene and there was no crash.  I was able to save, close and reopen the project with no issues.

**Comment by martin-damien** [comment]
I retried today, with "…" and unbreakable spaces and no error happened.

I close this issue until I'm able to reproduce and to provide you a text that cause crash.

Sorry for the waste of time.

**Comment by gedakc** [comment]
Thanks @martin-damien for reporting back that you were unable to recreate the issue and hence closed it.

If it does recur, please feel free to re-open this issue or create a new issue and describe the steps that you take to cause the crash.
