### ISSUE TITLE
pandoc export crashes if project title is empty

### ISSUE THREAD

**Issue by franapoli** [olivierkes/manuskript#535]
If the "Title" field is left empty in "Book information", no pandoc export format will work. I am running Manuskript 0.8 on Ubuntu 18.10.

**Comment by worstje** [comment]
Do you get a specific error in the log? Does a window popup? Does it silently fail?

I'll see if I can reproduce it later.

**Comment by gedakc** [comment]
Confirmed crash with Manuskipt 0.9.9 on Ubuntu 16.0 with the following steps:

1. Start manuskript and create new project using **Novel** template.

2. On **General** pane confirm that there is no text beside **Title**.  

3. Select **File -> Compile**.  

4. Set **Export to** to _Pandoc - HTML_.

5. Click **Preview** button.

6. Pandoc crashes.

Console log as follows:
```
$ bin/manuskript 
Debug: Web rendering engine used: QWebView
Running manuskript version 0.9.0.
Found translation in settings: 
Note: No translator found or loaded from system locale for locale en_CA.
Last accessed directory "/home/gedakc/tmp" loaded.
Project d3.msk saved.
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/ui/exporters/exporter.py", line 101, in preview
    F.preview(self.settingsWidget, self.previewWidget)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/exporter/pandoc/HTML.py", line 35, in preview
    html = self.output(settingsWidget)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/exporter/pandoc/abstractPlainText.py", line 41, in output
    return self.exporter.convert(src, args, outputfile)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/exporter/pandoc/__init__.py", line 71, in convert
    args.append("--metadata=title:{}".format(mainWindow().mdlFlatData.item(0, 0).text().strip()))
AttributeError: 'NoneType' object has no attribute 'text'
```
