### ISSUE TITLE
Python issues? lxml

### ISSUE THREAD

**Issue by rayfield** [olivierkes/manuskript#541]
Under Ubuntu 16.04, Manuskript had been working fine -- I've grown quite fond of this program in the few months I've been using it -- until recently:

raphael@Swann-Ubuntu:~$ manuskript 
Debug: Web rendering engine used: QTextEdit
Running manuskript version 0.8.0.
Note: No translator found or loaded for locale en_US.
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 99, in run
    app, MW = prepare()
  File "/usr/share/manuskript/manuskript/main.py", line 67, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 16, in <module>
    from manuskript import loadSave
  File "/usr/share/manuskript/manuskript/loadSave.py", line 9, in <module>
    import manuskript.load_save.version_0 as v0
  File "/usr/share/manuskript/manuskript/load_save/version_0.py", line 13, in <module>
    from lxml import etree as ET
ImportError: cannot import name 'etree'

lxml seems to be installed:

`raphael@Swann-Ubuntu:~$ pip install lxml
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (3.5.0)`

I suspect that my Python(s) setup may be slightly corrupted, as I've had some issues with other programs, such as my-weather-indicator, but I don't really know -- guidance diagnosing this issue is welcome.

**Comment by rayfield** [comment]
In case someone else has this problem, uninstalling and then reinstalling lxml (found this in StackOverflow) did it -- 

first 
sudo -H pip3 uninstall lxml

then
pip3 install --user lxml

**Comment by gedakc** [comment]
Thanks @rayfield for reporting back with how your fixed the lxml problem.
