### ISSUE TITLE
Unusual environment failure

### ISSUE THREAD

**Issue by DonEdwards** [olivierkes/manuskript#547]
Manuskript 0.8.0 running on Debian Linux... within UserLand on Android.

Manuskript started from the menu, fails with nothing visible happening.

I started it from a command prompt, with stdout and stderr redirected into the same file. Here's the result:

Qt: XKEYBOARD extension not present on the X server.
Debug: Web rendering engine used: QWebView
Running manuskript version 0.8.0.
Note: No translator found or loaded for locale C.
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 99, in run
    app, MW = prepare()
  File "/usr/share/manuskript/manuskript/main.py", line 67, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 21, in <module>
    from manuskript.settingsWindow import settingsWindow
  File "/usr/share/manuskript/manuskript/settingsWindow.py", line 19, in <module>
    from manuskript.ui.editors.themes import createThemePreview
  File "/usr/share/manuskript/manuskript/ui/editors/themes.py", line 13, in <module>
    from manuskript.ui.views.MDEditView import MDEditView
  File "/usr/share/manuskript/manuskript/ui/views/MDEditView.py", line 10, in <module>
    from manuskript.ui.views.textEditView import textEditView
  File "/usr/share/manuskript/manuskript/ui/views/textEditView.py", line 18, in <module>
    import enchant
  File "/usr/lib/python3/dist-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/usr/lib/python3/dist-packages/enchant/_enchant.py", line 52, in <module>
    from ctypes import *
  File "/usr/lib/python3.5/ctypes/__init__.py", line 537, in <module>
    _reset_cache()
  File "/usr/lib/python3.5/ctypes/__init__.py", line 276, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError

**Comment by gedakc** [comment]
The first message in the console log indicates a problem with keyboard input:
```
Qt: XKEYBOARD extension not present on the X server.
```

Without keyboard input there is no useful way to interact with the Manuskript application.

I believe you will need to fix the problem with "_Qt: XKEYBOARD extension not present on the X server._" before Manuskript will work.

Closing this issue as setting up a working Qt environment is outside the scope of the Manuskript application.
