### ISSUE TITLE
story line feature crashing

### ISSUE THREAD

**Issue by mxamber** [olivierkes/manuskript#620]
I was going to play around with the story line feature but found it blank, despite having multiple plots set up. It merely shows a blank white area at the bottom, touching either the refresh button or the scale slider immediately crashes the program. I found someone describing a similar issue [on the website](http://www.theologeek.ch/manuskript/2016/02/28/story-line/#comment-15069). Upon crash, after I pressed the refresh button, the console printed the following error:

`Traceback (most recent call last):`
`  File "manuskript\ui\views\storylineView.py", line 224, in refresh`
`  File "manuskript\ui\views\storylineView.py", line 184, in listItems`
`  File "manuskript\models\eferences.py", line 503, in tooltip`
`ValueError: expected '}' before end of string`

The same happened upon moving the slider, giving the same error. I was using Manuskript 0.9.0. on Windows 7.

**Comment by mxamber** [comment]
> Please provide the whole console log including the line where manuskript.exe is started.

I tried to (`manuskript.exe > log_plot.txt`) but the resulting log file is empty. The console window closes too fast for me to read what it's saying. Everything prior to the crash reads as follows:

`Debug: Web rendering engine used: QWebView`
`Running manuskript version 0.9.0.`
`Found translation in settings:`
`Loaded translation from system locale: manuskript_de_DE.qm.`
`Loading: path/to/my/project`
`Detected file format version: 1. Zip: True.`
`Projekt path/to/my/project geladen.`

(the issue with no translation found and it loading default locale is described already in issue #619 )

> Also check the **Help -> About** menu and provide the Software Versions in Use. 

- Manuskript 0.9.0.
- Python 3.4.4.
- PyQt 5.5.1
- Qt 5.5.1

**Comment by mxamber** [comment]
```G:\Programs\manuskript>manuskript.exe
Debug: Web rendering engine used: QWebView
Running manuskript version 0.9.0.
Found translation in settings:
Loaded translation from system locale: manuskript_de_DE.qm.
Loading: path/to/project.msk
Detected file format version: 1. Zip: True.
Projekt path/to/project.msk geladen.
Traceback (most recent call last):
  File "manuskript\ui\views\storylineView.py", line 224, in refresh
  File "manuskript\ui\views\storylineView.py", line 184, in listItems
  File "manuskript\models\references.py", line 503, in tooltip
ValueError: expected '}' before end of string```

**Comment by mxamber** [comment]
I opened the book-of-acts demo project that came with Manuskript and could recreate the issue. Same version (0.9.0. win32) as yours.

**Comment by mxamber** [comment]
> There might be something amiss with the Manuskript install on your computer. You might try deleting the Manuskript application (not your project), re-downloading Manuskript, and then re-installing Manuskript to see if that fixes the problem.

Issue persists. I screenrecorded it but for whatever reason YouTube won't finish processing the video :/

**Comment by mxamber** [comment]
https://www.youtube.com/watch?v=Vk5CQa6Nfoc

**Comment by mxamber** [comment]
> In the meantime, you might consider:
> 
> * Not using the Story line feature yet
> * Selecting a different language translation (removing the _manuskript_de.qm_ and _manuskript_de.ts_ files from the _i18n_ folder to default to English)
> * [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) and select the **develop** branch
> 
> Please let us know how you make out.

I went with not using the story line feature. Since it's to do with the German translation, which I already had another issue with (#619), I decided to just keep things as they are for now.
