### ISSUE TITLE
Manuskript fails to lauch on Windows

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#7]
(Reported anonymously)

Windows7 32bit, mansukript 0.2.0

> C:\manuskript>manuskript
> Failed to load translator for en_US...
> True
> ['C:/manuskript/icons', ':/icons', 'C:\\manuskript\\icons']
> Traceback (most recent call last):
>   File "", line 13, in
>   File "manuskript\main.py", line 56, in run
>   File "manuskript\main.py", line 62, in launch
>   File "manuskript\mainWindow.py", line 53, in __init__
>   File "manuskript\ui\mainWindow.py", line 168, in setupUi
>   File "manuskript\ui\views\textEditView.py", line 79, in __init__
>   File "site-packages\enchant\__init__.py", line 555, in __init__
>   File "site-packages\enchant\__init__.py", line 168, in __init__
>   File "site-packages\enchant\__init__.py", line 562, in _init_this
>   File "site-packages\enchant\__init__.py", line 307, in _request_dict_data
>   File "site-packages\enchant\__init__.py", line 256, in _raise_error
> enchant.errors.DictNotFoundError: b'invalid tag character found'
> manuskript returned -1

**Comment by olivierkes** [comment]
Corrected in develop. Will be released in 0.3.0.
