### ISSUE TITLE
Project won't open

### ISSUE THREAD

**Issue by Biep** [olivierkes/manuskript#732]
I created a project, and copied a lot of my material in it, and now it refuses to open.  It was in a single file, and the errors given were:
```
Debug: Web rendering engine used: QWebView
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Running manuskript version 0.9.0.
Loaded translation from system locale: manuskript_nl_NL.qm.
Last accessed directory "/home/biep/PB/Werk/Varia/Janboel/Manuskript" loaded.
Loading: /home/biep/PB/Werk/Varia/Janboel/Manuskript/Inhoud.msk
Detected file format version: 1. Zip: False.
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 163, in openFile
    self.mw.loadProject(filename)
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 565, in loadProject
    self.loadDatas(project)
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 792, in loadDatas
    errors = loadSave.loadProject(project)
  File "/usr/share/manuskript/manuskript/loadSave.py", line 66, in loadProject
    v1.loadProject(project, zip=isZip)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 883, in loadProject
    appendRevisions(mdl, root)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  [Previous line repeated 2 more times]
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 969, in appendRevisions
    ID = root.attrib["ID"]
  File "src/lxml/etree.pyx", line 2478, in lxml.etree._Attrib.__getitem__
KeyError: 'ID'
```
I opened the project file as an archive, copied its contents into a directory, and created a one-byte project file, but the issue remains:
```
Debug: Web rendering engine used: QWebView
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Running manuskript version 0.9.0.
Loaded translation from system locale: manuskript_nl_NL.qm.
Last accessed directory "/home/biep/PB/Werk/Varia/Janboel/Manuskript" loaded.
Loading: /home/biep/PB/Werk/Varia/Janboel/Manuskript/Inhoud.msk
Detected file format version: 1. Zip: False.
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 163, in openFile
    self.mw.loadProject(filename)
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 565, in loadProject
    self.loadDatas(project)
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 792, in loadDatas
    errors = loadSave.loadProject(project)
  File "/usr/share/manuskript/manuskript/loadSave.py", line 66, in loadProject
    v1.loadProject(project, zip=isZip)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 883, in loadProject
    appendRevisions(mdl, root)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  [Previous line repeated 2 more times]
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 969, in appendRevisions
    ID = root.attrib["ID"]
  File "src/lxml/etree.pyx", line 2478, in lxml.etree._Attrib.__getitem__
KeyError: 'ID'
```

**Comment by gedakc** [comment]
I just came across this issue report while searching for similar problems to recently reported issue #761.

If you are still trying to recover data from your project you might look at issue #761 which contains some advice on a path forward.
