### ISSUE TITLE
Opening on mac

### ISSUE THREAD

**Issue by Wv369** [olivierkes/manuskript#743]
followed the instructions and opened the manuskrip file, the terminal appeared and showed this:

users-Air:~ user$ /Users/user/Downloads/manuskript/manuskript ; exit;
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "manuskript/main.py", line 63, in run
  File "manuskript/main.py", line 69, in launch
  File "manuskript/mainWindow.py", line 51, in __init__
  File "manuskript/ui/mainWindow.py", line 167, in setupUi
  File "manuskript/ui/views/textEditView.py", line 79, in __init__
  File "enchant/__init__.py", line 548, in __init__
enchant.errors.Error: No tag specified and default language could not be determined.
manuskript returned -1
logout

[Process completed]

And nothing happened

**Comment by gedakc** [comment]
Based on the console messages it would appear that an old version of Manuskript is being used.  The "Warning: failed to load..." message was changed quite a number of versions ago.

I suggest you try the most recent version (0.11.0) and run from source code.  Otherwise you might try an older (0.10.0) version for which a PyInstaller package is available.
