### ISSUE TITLE
Creating new project fails

### ISSUE THREAD

**Issue by szopeno** [olivierkes/manuskript#76]
I have downloaded manuskript, created a sample project (succesfully). I had a bit of fun with it, then I closed manuskript, deleted the project by hand, started manuskript, opened sample project "book of acts", closed it and tried to create new project. Failed. IN terminal, the following output was generated:

Traceback (most recent call last):
  File "manuskript/ui/welcome.py", line 159, in createFile
  File "manuskript/ui/welcome.py", line 344, in loadDefaultDatas
  File "manuskript/ui/welcome.py", line 344, in <listcomp>
IndexError: list index out of range

Since that time I tried restarting manuskript etc, but creating projects always fails.

**Comment by olivierkes** [comment]
Thanks. This has been corrected in develop branch.
