### ISSUE TITLE
Manuskript Crashed, Now Refuses To Open File

### ISSUE THREAD

**Issue by EMFrey** [olivierkes/manuskript#761]
Hi there.

I love using Manuskript, and am very grateful to its developer for creating and sharing it so generously. It's a brilliant program, and I appreciate very much that it is available at all, let alone for free. I can't state that enough.

Unfortunately, today, it has caused me an issue which has been exceedingly troubling. It is less troubling now that I followed directions that allowed me to at least view individual text files inside and know that the writing I had done does, in fact, remain accessible in some form, but it will be a great deal of work to put it all back into the document and organize it again. I am really hoping that it might be possible to address whatever corruption or so forth might be the problem directly so that I can simply open the document again in Manuskript.

Here is what occurred: While I was using the program, I was creating various pages and folders and assigning names and icons to them, as well as deleting certain unwanted pages I had created in error while trying to paste duplicates of other folders and occasionally manually saving. It was then that Manuskript quit without warning.

Because I was working fast and repeating all of those various actions multiple times in quick succession, I cannot remember at precisely which one of them I was doing at the moment the program quit -- but I believe it to have been during one of those actions as opposed to simply typing content in the body of a page, creating a new document, etc. (if this distinction matters at all).

I searched here for an answer and tried a few different things. The last thing that I did was to open Command Prompt as I had seen advised and pasted the file path.

When I entered the information, it told me:

Detected file format version: 1. Zip: True.
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 83, in showEvent
  File "manuskript\mainWindow.py", line 565, in loadProject
  File "manuskript\mainWindow.py", line 792, in loadDatas
  File "manuskript\loadSave.py", line 66, in loadProject
  File "manuskript\load_save\version_1.py", line 883, in loadProject
  File "manuskript\load_save\version_1.py", line 964, in appendRevisions
  File "manuskript\load_save\version_1.py", line 964, in appendRevisions
  File "manuskript\load_save\version_1.py", line 969, in appendRevisions
  File "lxml.etree.pyx", line 2366, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:62258)
KeyError: 'ID'

C:\Users\user>

I have now downloaded Version 0.11.0 and will be using that from now on, and hopefully this problem won't be an issue, but in the meantime, any information you can give me about how I might get this document back intact, if such is possible, will be greatly appreciated.

Thank you so much for all of your work.

**Comment by gedakc** [comment]
'Sorry to hear your project stopped loading, but glad to learn you discovered how to gain access to your work in the project file.

The following messages in the console log indicate a problem with the revision history:

```
File "manuskript\loadSave.py", line 66, in loadProject
File "manuskript\load_save\version_1.py", line 883, in loadProject
File "manuskript\load_save\version_1.py", line 964, in appendRevisions
File "manuskript\load_save\version_1.py", line 964, in appendRevisions
File "manuskript\load_save\version_1.py", line 969, in appendRevisions
File "lxml.etree.pyx", line 2366, in lxml.etree._Attrib.getitem (src\lxml\lxml.etree.c:62258)
KeyError: 'ID'
```

From these messages I assume you either started your project using Manuskript 0.9.0 or earlier, or you manually enabled the **Keep revisions** setting.  With 0.10.0 and higher **Keep revisions** is disabled by default.

Unfortunately there are problems with the revision code, such that we decided to disable the feature by default.

Issue #529 indicates how to gain access to the project work, and also contains a recovered project.  Unfortunately the steps to recover a project were not documented.

At this point I see at least three options:

1. Go back to your last known good backup of the project file and use that as your base going forward.

2. Try to restore the project:

   You might examine the manuskript source code to learn the project storage structure and determine steps to restore the project to working order.

   You might try the steps from [issue319](https://github.com/olivierkes/manuskript/issues/319#issuecomment-366774753).  Note that we never received a report back from the user to indicate if the steps worked.

   Further in issue #529 it references that the revision history was lost when restoring the project.  Perhaps @worstje might see this post and offer to help.

3. Try to recreate the project:

   You might create a new manuskript project.  Then manually recreate each folder, scene, character, etc, by copying text from the extracted non-working project and pasting it into the appropriate section of the new project.

If you do figure out the steps to restore the project then consider sharing these so that other Manuskript users can benefit from your work.

**Comment by EMFrey** [comment]
Hi there, Gedakc!

Thank you so much for your suggestions. Yes, I was using Version 9. I downloaded 0.11.0 now and will begin to use it.

Unfortunately, my feeble abilities in matters of a technical nature precluded me from understanding almost anything you or those who answered in the other threads said. All I got out of it is, "anything I can find having to do with 'revisions' is bad."

Last night, before posting here, I copied the original .msk file and started messing around with it, and was able to access the individual files (that had text that was actually readable) by changing the extension of the .msk file to .zip and then unzipping it, as recommended in another issue thread here. After failing to accomplish any more than being able to find my text in some form (which I was already exceedingly happy about), I then changed the extension of the containing folder (whose extension I had changed from .msk to .zip) back to an .msk extension, figuring I could mess around with it however I wanted since I had multiple copies already and wasn't gaining any additional benefit from it. I'm not sure if changing it back did anything or not, as it was not recognized by Manuskript as a Manuskript file, but wanted to throw that detail in there in case it is pertinent and I just don't know it.

Now, understanding nothing but "revisions bad" but still ready to try, I went back to this folder and found a file called "revisions," which was filled with snippets of text from the original document that crashed, and deleted this file. I opened Manuskript and attempted to load the so-called ".msk" file in question -- which I believe was really just a zip folder which humored me by displaying a ".msk" extension only because I had told it to manually. Manuskript did not immediately recognize the file when I searched for it, so I changed the settings to display "all files" as opposed to only ".msk" files. The file I wanted then displayed, opened, and loaded (so far as I can see) perfectly -- as though nothing ever happened at all.

I am shocked that this worked and have absolutely no idea why it did, but I'm very happy to see all of the information that I cared about back. I don't know if this update will help anybody in the future, but I'd like to think that it might if somebody can make any sense of it.

Now that I have the document open and working again, what settings would you suggest I keep in the "Revisions" tab under settings to avoid having this problem recur?

Thank you so much for taking the time to reply and for all your suggestions!!!

**Comment by worstje** [comment]
Manuskript .msk files are just zip files, assuming you have the single file option turned on in the settings. Renaming to .zip allows you to open it with any program. (Newer generation Microsoft formats like Docx for Word and Xlsx for Excel pull the same trick to store their data.)

What you did to delete the **revisions.xml** file is indeed how I have solved the same problem in the past, and is the 'correct' way of resolving the issue.

## Duplicate IDs

The duplicate IDs is something I have seen before but don't quite recall the cause of. I think it may have been a side-effect of bugs in the folders and texts behaviour when moving and copying them, but I don't quite recall. Resolving it is unfortunately not as trivial as the other issue.

IDs are unique numbers used to refer to texts so that you can rename and move them without Manuskript having to go through every single text in your project to see if you referenced it and adjust the reference in those files. But what happened here is that you ended up with two texts that are represented by the same unique number, which should never happen but probably happened because of the previously mentioned bug. Which IIRC should be fixed in 0.10 onwards, but simply fixing the sink so it does not leak doesn't clean up the mess it caused.

Unfortunately it seems the loading mechanism only checks for duplicate IDs as a sanity-check to verify project integrity, and was not designed to track the texts causing the conflicts, making it more troublesome than it should be for a non-programmer to address the exact problem.

I'm willing to look at & fix your project. If you aren't willing to share your project on a public forum like github (which is quite understandable!) you can find me in the unofficial Manuskript Discord as well.

## Revision stuff

My recommendation is to **keep the revision setting turned off for the time being**. I remember digging into the code last year and the conclusion was that it was a huge source of slowdowns while saving on Windows especially. Additionally, any bugs in the saving process that weren't properly handled could lead to crashes, causing the corrupted revisions file you have taken note of. (Which reminds me:, the 'store as single file' option tends to completely destroy projects if a bug happens while saving, which is why I try to keep that setting turned off myself.)

Unless something happened in the last couple of months with us attracting fresh development blood (admittedly, I haven't paid much attention due to other things happening in my life), the revisions and even saving code are still at the point where someone needs to invest some time into them to properly tackle the architectural Manuskript is suffering from. (Or was suffering from; maybe someone already took case of those issues while I wasn't paying attention!)

Finally, I want to say that while all of this might sound like I am calling Manuskript a really unreliable tool, it is more that I have fixed a fair few bugs and cleaned up a number of messes in my time. As a result, I know exactly where the proverbial pants are most likely to rip while bending over. 😄

**Comment by siliconserf** [comment]
I've also had experience recovering from the duplicate ID problem. You can message me and arrange to send a copy of your project. Having used the program from somewhere around 0.7 or so I can also say I like working with the software and trust it (though I back up frequently - even the best software can and sometimes will blow your file to bits. Not to mention hardware failures.)

**Comment by gedakc** [comment]
@EMFrey it's good you were able to recover your project data.  To repeat what was already recommended, disable the **Keep revisions** setting, and disable the **Save to one single file** setting.  Also make a backup at the end of your writing sessions to avoid loss of work due to software bugs, power outages, or hardware failure.

The issue with duplicate ID's is more difficult to fix, both in your project and in the manuskript code.  The problem arises if one copies and pastes a complete folder or scene because these new objects do not appear to be assigned a new ID.  The problem does not arise if you copy only the text from within a scene.  For anyone trying to learn more about this problem see issue #324 which contains steps to reproduce the problem.
