### ISSUE TITLE
(l)ubuntu dependencies for develop branch

### ISSUE THREAD

**Issue by trivers** [olivierkes/manuskript#81]
Hi,
The dependencies I needed for lubuntu 16.04 (32 and 64bit) where a little different than those listed in the read me, for using the develop branch.

I also needed to have 'python3-pyqt5.qtwebkit'

This is what gets it running:
`sudo apt install python3-pyqt5 libqt5svg5 python3-lxml python3-enchant zlib1g python3-pyqt5.qtwebkit`

It's possible this is also what is needed for other *buntu distros, but I have not tested that;)

**Comment by Renkineko** [comment]
Not needed on my ubuntu mate 16.04. Maybe it could help on my xubuntu, i'll test it later.

**Comment by yarko** [comment]
on my 16.04, this (nor other things) have worked.

Also, looking at `makefile`, I not there is no manuskript/setup.py

python-3.6;
python  PyQt5 doesn't have interface for PyQt5.QtWebKitWidgets:

```
~/workspace/writing/manuskript$ bin/manuskript 
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "bin/manuskript", line 13, in <module>
    main.run()
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/main.py", line 63, in run
    launch()
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/main.py", line 67, in launch
    from .mainWindow import MainWindow
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/mainWindow.py", line 22, in <module>
    from manuskript.ui.exporters.exporter import exporterDialog
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/ui/exporters/exporter.py", line 10, in <module>
    from manuskript import exporter
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/exporter/__init__.py", line 4, in <module>
    from manuskript.exporter.manuskript import manuskriptExporter
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/exporter/manuskript/__init__.py", line 6, in <module>
    from manuskript.exporter.manuskript.HTML import HTML
  File "/home/yarko/workspace/writing/manuskript/bin/../manuskript/exporter/manuskript/HTML.py", line 4, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by olivierkes** [comment]
Thanks, added to the readme.
