### ISSUE TITLE
Crash on showing settingsWindow.py

### ISSUE THREAD

**Issue by DarkRedman** [olivierkes/manuskript#817]
When I try to show the settings window I get a crashed so I launched the program in terminal and here's the traceback :

```
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 1440, in settingsWindow
    self.sw = settingsWindow(self)
  File "/usr/share/manuskript/manuskript/settingsWindow.py", line 65, in __init__
    [i.lower() for i in list(QStyleFactory.keys())]
ValueError: '' is not in list
Fatal Python error: Aborted

Current thread 0x00007f51ea476740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 221 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 234 in run
  File "/usr/bin/manuskript", line 30 in <module>
Abandon (core dumped)
```

I use the version 0.11.0, I checked the file settingsWindow.py at line 64 and somehow this part :

```python
qApp.style().objectName()
```

could return an empty string so I fixed it this way to fallback to the 0 index

```python
try:
            self.cmbStyle.setCurrentIndex(
                [i.lower() for i in list(QStyleFactory.keys())]
                .index(qApp.style().objectName()))
        except ValueError:
            self.cmbStyle.setCurrentIndex(0)
```

**Comment by TheJackiMonster** [comment]
I have added the fix for this with the newest commit d27910449d80bb176a05c45a40261d6c5ec3033c. So the next release should not crash like that.
