### ISSUE TITLE
on Fedora 25 Manuskript doesn't start

### ISSUE THREAD

**Issue by Yattatux** [olivierkes/manuskript#82]
Fedora 25 Workstation (Gnome) - 64bit, all dependencies installed (optional too)
This is the error message in Terminal:

```
[antares@localhost 01-manuskript]$ ./manuskript
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "manuskript/main.py", line 8, in <module>
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /lib64/libGL.so.1: undefined symbol: drmFreeDevice
manuskript returned -1
[antares@localhost 01-manuskript]$
```

**Comment by olivierkes** [comment]
Hi,
This is an issue with the package.
You should try running from source ([Here is an idea on how to do it in Ubuntu](https://github.com/olivierkes/manuskript/wiki/Installation-on-Linux-(Ubuntu)), shouldn't be very different on Fedora)

**Comment by Yattatux** [comment]
Hi Olivier
I solved erasing the `libdrm.so.2` file from manuskript folder.

**Comment by olivierkes** [comment]
Great, I'll close that for now, will see with the next package how it goes.
