### ISSUE TITLE
crashing on initial save (again?)

### ISSUE THREAD

**Issue by relogi** [olivierkes/manuskript#88]
On Antergos(Arch linux (Python 3.6.0) both with the latest release and the git version I start the program, select novel (or any selection, I tried several) and press "create". The program crashes after I have selected a file name and press "save".

**Comment by relogi** [comment]
I thought maybe I had a dependency problem so:
[rg@archlen ~]$ sudo pacman -S --needed python python-pyqt5 qt5-svg python-lxml python-pyenchant zlib
[sudo] password for rg: 
warning: python-3.6.0-2 is up to date -- skipping
warning: python-pyqt5-5.8-1 is up to date -- skipping
warning: qt5-svg-5.8.0-1 is up to date -- skipping
warning: python-lxml-3.7.3-1 is up to date -- skipping
warning: python-pyenchant-1.6.8-2 is up to date -- skipping
warning: zlib-1:1.2.11-1 is up to date -- skipping
 there is nothing to do

Maybe this will help. I am too noob to know what this is, much less start the troubleshooting. Any help would be appreciated:

Traceback (most recent call last):
  File "/home/rg/Downloads/manuskript-master/bin/../manuskript/ui/welcome.py", line 159, in createFile
    self.loadDefaultDatas()
  File "/home/rg/Downloads/manuskript-master/bin/../manuskript/ui/welcome.py", line 344, in loadDefaultDatas
    t = [i for i in self.templates() if i[0] == self.template[0]]
  File "/home/rg/Downloads/manuskript-master/bin/../manuskript/ui/welcome.py", line 344, in <listcomp>
    t = [i for i in self.templates() if i[0] == self.template[0]]
IndexError: list index out of range
Fatal Python error: Aborted

Current thread 0x00007f384092a400 (most recent call first):
  File "/home/rg/Downloads/manuskript-master/bin/../manuskript/main.py", line 72 in launch
  File "/home/rg/Downloads/manuskript-master/bin/../manuskript/main.py", line 63 in run
  File "/home/rg/Downloads/manuskript-master/bin/manuskript", line 13 in <module>
Aborted (core dumped)

**Comment by olivierkes** [comment]
I think you're still using the 0.3.0 
With the git version, you have to use the develop branch (git checkout develop).
