### ISSUE TITLE
App crashing when adding detailed info to character.

### ISSUE THREAD

**Issue by lucasshiva** [olivierkes/manuskript#920]
The app crashes when I have more entries in **Detailed Info** than the number of Characters. For example, If I have only one (1) character, I can't have more than one (1) entry in **Detailed Info** as the app crashes and I get the following error message: 
```
An unhandled exception has occurred!
Traceback (most recent call last):
  File "/opt/manuskript/bin/../manuskript/models/characterPOVModel.py", line 17, in filterAcceptsRow
    return self.sourceModel().pov(sourceRow)
  File "/opt/manuskript/bin/../manuskript/models/characterModel.py", line 139, in pov
    return self.character(row).pov()
  File "/opt/manuskript/bin/../manuskript/models/characterModel.py", line 124, in character
    return self.characters[row]
IndexError: list index out of range
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/opt/manuskript/bin/../manuskript/models/characterPOVModel.py", line 17, in filterAcceptsRow
    return self.sourceModel().pov(sourceRow)
  File "/opt/manuskript/bin/../manuskript/models/characterModel.py", line 139, in pov
    return self.character(row).pov()
  File "/opt/manuskript/bin/../manuskript/models/characterModel.py", line 124, in character
    return self.characters[row]
IndexError: list index out of range
```

I got the same problem in Windows 10 (with the latest executable) and Arch Linux (installing from source). This is the logging information I get when running the app in Arch Linux:
```
** (process:93464): WARNING **: 18:03:15.281: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (process:93464): WARNING **: 18:03:15.282: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (process:93464): WARNING **: 18:03:15.282: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

Logging to STDERR.
Logging to file: /home/lucas/.local/share/manuskript/manuskript/logs/2021-08-15_18-03-15_manuskript#93464.log
Operating System: Linux-5.13.9-zen1-1-zen-x86_64-with-glibc2.33
Hardware: x86_64 / 
Running from unpackaged source code.
* sys.executable = '/usr/bin/python3'
* sys.argv = ['/usr/bin/manuskript']
* sys.path = ['/opt/manuskript/bin',
 '/opt/manuskript/bin/..',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/home/lucas/.local/lib/python3.9/site-packages',
 '/usr/lib/python3.9/site-packages']
* sys.prefix = '/usr'
Manuskript 0.12.0 (Python 3.9.6)
* PyQt 5.15.4 (compiled against Qt 5.15.2)
  * Qt 5.15.2 (runtime)
* lxml.etree 4.6.3.0
  * libxml   2.9.10 (compiled: 2.9.10)
  * libxslt  1.1.34 (compiled: 1.1.34)
* pyEnchant 3.2.1 (libenchant: 2.3.0)
* pySpellChecker N/A
* Symspellpy N/A
* Markdown 3.3.4
Web rendering engine: QTextEdit
Preferred translation: ['en-US'] (based on available ui languages)
Using the builtin translation. (U.S. English)
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

**Comment by lucasshiva** [comment]
I analyzed the code and saw some differences between what was written and what the error message was reporting. So, I realized I was **NOT** using the Latest/develop version. I assumed the AUR package [manuskript-git](https://aur.archlinux.org/packages/manuskript-git/) was using said version, but it appears like this package is using the master branch. 

Installing the app from source (manually) seems to fix the problem I was having.

**Comment by TheJackiMonster** [comment]
From my experience the *-git packages in the AUR usually use a stable branch. So the most difference in case of Manuskript is that it will build everything from source instead of using the released binaries.

Other projects may push more frequently to the master branch. However Manuskript only merges the final releases to it because the develop branch can sometimes be unstable.
