### ISSUE TITLE
After close project, open or create project fails

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#96]
After closing a project in Manuskript, a welcome window is shown prompting to either open an existing project or create a new project.

When I select a project type (for example **Novel**) and click **Create** a new project, I am prompted and then select a directory and filename.  When I click **save** I am returned to the welcome window.

Following are the messages from the terminal in which I started manuskript:

```
$ manuskript &
[1] 5359
$ Warning: failed to load translator for locale en_CA...
Loading: /home/gedakc/tmp/manuskript-test.msk
Detected file format version: 1. Zip: False.
Project /home/gedakc/tmp/manuskript-test.msk loaded.
Project /home/gedakc/tmp/manuskript-test.msk saved.
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/ui/welcome.py", line 160, in createFile
    self.mw.loadProject(filename, loadFromFile=False)
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/mainWindow.py", line 314, in loadProject
    self.makeConnections()
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/mainWindow.py", line 605, in makeConnections
    self.btnAddSubPlot.clicked.connect(self.updateSubPlotView, AUC)
TypeError: connection is not unique

[1]+  Done                    manuskript
$
```
A similar error message is shown if I try to open another existing project.

From the error message it appears that some stuff from the old project is not cleared out or initialized.

I am working with the latest May 8, 2017 **develop** branch:
```
commit 9a646cb40342ebaa861362dd64d008157b6ca7a7
Preview can display images in html relative to project path (temporary solution for #22)
```

To work around this issue:

1. Close project
2. Close Manuskript
3. Start Manuskript
4. Open or create new project

**Comment by gedakc** [comment]
@olivierkes, the following patch is a work-in-progress as I do not yet know if it is the correct way to fix this issue.

To create this patch I used a technique previously used in the code to work around TypeErrors for Characters.  See [manuskript/mainWindow.py - line 568](https://github.com/olivierkes/manuskript/blob/master/manuskript/mainWindow.py#L568) for the **try** and **except** handling example.

The patch can be applied by copying the below text, pasting it into a file (say issue96-draft1.patch), and then applying with `git am issue96-draft1.patch`.

When I used this patch, I am able to close one project and then open another, all the while keeping the manuskript program running.

Does this seem like the correct approach to this issue?

Curtis

```
From 754c2c85fe59b7210ddb327068e1a020db12b797 Mon Sep 17 00:00:00 2001
From: Curtis Gedak <gedakc@gmail.com>
Date: Wed, 10 May 2017 12:44:36 -0600
Subject: [PATCH 1/1] Fixes: after project close, open or create project fails

---
 manuskript/mainWindow.py | 18 +++++++++++++++---
 1 file changed, 15 insertions(+), 3 deletions(-)

diff --git a/manuskript/mainWindow.py b/manuskript/mainWindow.py
index 2499ae7..2dc84ab 100644
--- a/manuskript/mainWindow.py
+++ b/manuskript/mainWindow.py
@@ -602,7 +602,11 @@ class MainWindow(QMainWindow, Ui_MainWindow):
         self.btnRmPlot.clicked.connect(lambda:
                                        self.mdlPlots.removePlot(self.lstPlots.currentPlotIndex()), AUC)
         self.btnAddSubPlot.clicked.connect(self.mdlPlots.addSubPlot, AUC)
-        self.btnAddSubPlot.clicked.connect(self.updateSubPlotView, AUC)
+        try:
+            self.btnAddSubPlot.clicked.connect(self.updateSubPlotView, AUC)
+        except TypeError:
+            # Connection has already been made
+            pass
         self.btnRmSubPlot.clicked.connect(self.mdlPlots.removeSubPlot, AUC)
         self.lstPlotPerso.selectionModel().selectionChanged.connect(self.plotPersoSelectionChanged)
         self.btnRmPlotPerso.clicked.connect(self.mdlPlots.removePlotPerso, AUC)
@@ -662,11 +666,19 @@ class MainWindow(QMainWindow, Ui_MainWindow):
         self.storylineView.setModels(self.mdlOutline, self.mdlCharacter, self.mdlPlots)
 
         self.treeOutlineOutline.selectionModel().selectionChanged.connect(self.outlineItemEditor.selectionChanged, AUC)
-        self.treeOutlineOutline.clicked.connect(self.outlineItemEditor.selectionChanged, AUC)
+        try:
+            self.treeOutlineOutline.clicked.connect(self.outlineItemEditor.selectionChanged, AUC)
+        except TypeError:
+            # Connection has already been made
+            pass
 
         # Sync selection
         self.treeRedacOutline.selectionModel().selectionChanged.connect(self.redacMetadata.selectionChanged, AUC)
-        self.treeRedacOutline.clicked.connect(self.redacMetadata.selectionChanged, AUC)
+        try:
+            self.treeRedacOutline.clicked.connect(self.redacMetadata.selectionChanged, AUC)
+        except TypeError:
+            # Connection has already been made
+            pass
 
         self.treeRedacOutline.selectionModel().selectionChanged.connect(self.mainEditor.selectionChanged, AUC)
 
-- 
2.7.4

```

**Comment by olivierkes** [comment]
I merged your pull request, great work, thanks,
