### ISSUE TITLE
Cannot open my projects

### ISSUE THREAD

**Issue by eternalvoyageur** [olivierkes/manuskript#964]
I'm using Ubuntu. Today I wanted to open my project as usual, I choose the project from the dropdown list but Manuskript doesn't open it. The only way I can open the program is by creating a new project. When I do that. the File>Open and the File>Open Recent options are greyed out. I tried reinstalling put nothing helped. I tried to update to the latest version as per these instructions https://www.theologeek.ch/manuskript/download/ but I got the message error: cannot access archive 'manuskript-0.12.0-1.deb': No such file or directory
I'm a Linux beginner, so simple instructions would be very much appreciated. Thanks!

**Comment by TheJackiMonster** [comment]
On Ubuntu it's probably easiest to install Manuskript through the Ubuntu Software Center. You can get the version 0.11.0 as snap package or the version from regular repositories (might be older). I would recommend to stick to this if you're new to Linux.

Otherwise we have now a flatpak package shipping version 0.12.0 with most features. You can get this from [here](https://flathub.org/apps/details/ch.theologeek.Manuskript), once flatpak is installed and working on your system. You can follow this setup guide from flathub [here](https://flatpak.org/setup/Ubuntu/). But it requires to use a terminal unfortunately.

> Today I wanted to open my project as usual, I choose the project from the dropdown list but Manuskript doesn't open it.

Was there any problem occuring opening the project via file selection from the startup dialog or anything?

**Comment by eternalvoyageur** [comment]
@TheJackiMonster Thanks for replying. I can use the terminal a bit, but just the simple basics. I can paste commands, use sudo, etc. Progress so far: if I install Manuskript via Muon Package Manager, I get the problems that I described in the top post (yes, it's the startup dialog that's not working, but also once I open the Program the File>Open option is grayed out). The version is 0.10.0 so it's probably too old and that'y why it stopped working, is my guess. 
When I install Manuskript via Ubuntu Software Center or Floatpack, it gets installed but I cannot open it at all. The Menu shortcut doesn't work, but also when I want to open my project file (right click, open with > Manuscript) it doesn't do anything either.

**Comment by TheJackiMonster** [comment]
Can you try to open Manuskript from terminal? Basically open a terminal, type `manuskript` and hit enter to start it. Maybe the output from any error is showing up which could help.

If you only get version 0.10.0 from your usual repositories, I would definitely recommend using snap or flatpak instead currently. Because those will ship their dependencies inside in the required versions. I would assume that your usual repositories only provide very old versions of the dependencies. So newer versions of Manuskript will probably fail to work with them.

**Comment by eternalvoyageur** [comment]
I tried to open Manuskript from the terminal, and the same problem happens (startup dialog doesn't let me open my project). I did uninstall the respository version and installed it via Snap, but the it didn't open at all.

**Comment by TheJackiMonster** [comment]
Ok, try to remove all versions currently installed and install the flatpak version. This should work from my experience.

**Comment by eternalvoyageur** [comment]
I finally managed to do this (Flatpak didn't want to do anything until I used sudo from the terminal) Unfortunately the same problem persists. I still cannot import any projects :(

**Comment by eternalvoyageur** [comment]
On Flatpak I'm getting this error when I try to import my project: CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/app/share/manuskript/bin/../manuskript/ui/welcome.py", line 165, in openFile
    self.mw.loadProject(filename)
  File "/app/share/manuskript/bin/../manuskript/mainWindow.py", line 605, in loadProject
    self.loadDatas(project)
  File "/app/share/manuskript/bin/../manuskript/mainWindow.py", line 891, in loadDatas
    errors = loadSave.loadProject(project)
  File "/app/share/manuskript/bin/../manuskript/loadSave.py", line 68, in loadProject
    v1.loadProject(project, zip=isZip)
  File "/app/share/manuskript/bin/../manuskript/load_save/version_1.py", line 632, in loadProject
    files = loadFilesFromZip(project)
  File "/app/share/manuskript/bin/../manuskript/load_save/version_0.py", line 187, in loadFilesFromZip
    files[os.path.normpath(f)] = zf.read(f)
  File "/usr/lib/python3.9/zipfile.py", line 1464, in read
    return fp.read()
  File "/usr/lib/python3.9/zipfile.py", line 908, in read
    buf += self._read1(self.MAX_N)
  File "/usr/lib/python3.9/zipfile.py", line 998, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid distance too far back

**Comment by eternalvoyageur** [comment]
Update: I found an older version of my project that I had uploaded to google drive. I could open this, so I am really relieved. I'm a bit terrified that it would happen again though.

@TheJackiMonster thanks a huge bunch for guiding me through this!

**Comment by TheJackiMonster** [comment]
That's a good result, I guess. Just make sure to backup your projects. Manuskript is still a software full of unknown errors to be honest. ^^'

I hope we can fix them but currently it's better to backup.
