### ISSUE TITLE
unable to use lxml on M1 mac

### ISSUE THREAD

**Issue by jrstrick** [olivierkes/manuskript#966]
The current version (0.12) is unable to use lxml on mac, due to the lxml binaries installed by homebrew's pip3 being compiled for intel macs.  The solution is to force pip to recompile lxml.

The error:
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/Users/jim/manuskript/bin/./manuskript", line 13, in <module>
    main.run()
  File "/Users/jim/manuskript/bin/../manuskript/main.py", line 305, in run
    app, MW = prepare(arguments)
  File "/Users/jim/manuskript/bin/../manuskript/main.py", line 41, in prepare
    manuskript.logging.logRuntimeInformation()
  File "/Users/jim/manuskript/bin/../manuskript/logging.py", line 353, in logRuntimeInformation
    from lxml import etree
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so: mach-o, but wrong architecture
	/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so: mach-o, but wrong architecture

The solution:
arch -arm64 /opt/homebrew/bin/pip3 uninstall lxml
arch -arm64 /opt/homebrew/bin/pip3 install lxml --no-cache-dir

**Comment by TheJackiMonster** [comment]
I assume this is actually something which should be fixed on side of pip itself. Maybe you can report it in the pip project. So it checks the systems architecture and installs the proper packages.

But I can link to this issue in the wiki as potential work-around. Thanks for providing this information.

**Comment by jrstrick** [comment]
Would this be more properly posted to the pip project or the lxml maintainers, do you think? I'm a python newb and I don't have clear understanding of who controls what.

**Comment by TheJackiMonster** [comment]
I'm not using pip as much to know that either. But I assume this is a problem of both. The maintainers of lxml and other packages should have an interest in providing binaries for the new architecture and pip should properly understand which packages it requires.

I mean it doesn't make sense to get x86 binaries installed by pip on an arm system. So they probably only check if it's identifier is containing "mac" or similar which would be an issue.

**Comment by Reaper10** [comment]
@TheJackiMonster is lxml built in?

**Comment by TheJackiMonster** [comment]
@Reaper10 lxml is a requirement but it won't be built in. This would require more advanced packaging and pre-compiling.

**Comment by TheFern2** [comment]
I didn't have this issue. I just used `pip3 install lxml` and app seems to run fine. So this might have been fixed.

**Comment by AlexanderThompsonRaux** [comment]
I kept getting `ModuleNotFoundError: No module named 'lxml' `

When I try to run `arch -arm64 /opt/homebrew/bin/pip3 uninstall lxml` as suggested I kept getting: `This environment is externally managed`

Even though lxml was installed with pip - I ran `brew install python-lxml` 
And it fixed the problem. 
Not sure however if I now have mutliple versions or instances of lxml. But hey, it works

**Comment by tangybit** [comment]
I got the `externally-managed` error running the `arch` command as well. `brew install python-lxml` gave me `No available formula with the name 'python-lxml'`. 

I ended up setting a `venv` and installed everything in there. Everything works beautifully now!

**Comment by peter88213** [comment]
Apart from that, is there anything against replacing the external *lxml* package with the built-in *xml.etree.ElementTree* module when refactoring the code?
