### ISSUE TITLE
Fail to launch

### ISSUE THREAD

**Issue by DargaardMS** [olivierkes/manuskript#967]
0.12.0 was working fine, I loaded it up on November 9th and it downloaded language tool, then crashed, has not launched since.  I have tried removing and reinstalling, I have removed language tool manually (renaming C:\Users\Dargaard\.cache\language_tool_python) that just causes another crash.

Here is the log from the 9th, After the log from the 9th I'll post the log from what currently happens.

021-11-09 00:01:30,582 - manuskript.logging - INFO - Logging to file: C:/Users/Dargaard/AppData/Local/manuskript/manuskript\logs\2021-11-09_00-01-30_manuskript#9404.log
2021-11-09 00:01:30,583 - manuskript - INFO - Operating System: Windows-10-10.0.19041-SP0
2021-11-09 00:01:30,583 - manuskript - INFO - Hardware: AMD64 / Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
2021-11-09 00:01:30,583 - manuskript - INFO - Running in a frozen (packaged) state.
2021-11-09 00:01:30,583 - manuskript - DEBUG - * sys.frozen = True
2021-11-09 00:01:30,584 - manuskript - DEBUG - * sys._MEIPASS = C:\ProgramData\chocolatey\lib\manuskript\tools\manuskript
2021-11-09 00:01:30,584 - manuskript - DEBUG - * sys.executable = 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\manuskript.exe'
2021-11-09 00:01:30,584 - manuskript - DEBUG - * sys.argv = ['C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\manuskript.exe']
2021-11-09 00:01:30,584 - manuskript - DEBUG - * sys.path = ['C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\base_library.zip',
 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\..',
 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\lib-dynload',
 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript']
2021-11-09 00:01:30,585 - manuskript - DEBUG - * sys.prefix = 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript'
2021-11-09 00:01:30,585 - manuskript - INFO - Manuskript 0.12.0 (Python 3.8.9)
2021-11-09 00:01:30,585 - manuskript - INFO - * PyQt 5.15.4 (compiled against Qt 5.15.2)
2021-11-09 00:01:30,585 - manuskript - INFO -   * Qt 5.15.2 (runtime)
2021-11-09 00:01:30,630 - manuskript - INFO - * lxml.etree 4.6.3.0
2021-11-09 00:01:30,630 - manuskript - INFO -   * libxml   2.9.5 (compiled: 2.9.5)
2021-11-09 00:01:30,630 - manuskript - INFO -   * libxslt  1.1.30 (compiled: 1.1.30)
2021-11-09 00:01:30,631 - manuskript - INFO - * pyEnchant 3.2.0 (libenchant: 2.2.7)
2021-11-09 00:01:30,631 - manuskript - INFO - * pySpellChecker 0.6.2
2021-11-09 00:01:30,631 - manuskript - INFO - * Symspellpy 6.7.0
2021-11-09 00:01:30,658 - manuskript - INFO - * Markdown 3.3.4
2021-11-09 00:01:30,659 - manuskript - INFO - Web rendering engine: QTextEdit
2021-11-09 00:01:30,678 - manuskript.main - INFO - Preferred translation: ['en-US'] (based on available ui languages)
2021-11-09 00:01:30,678 - manuskript.main - INFO - Using the builtin translation. (U.S. English)
2021-11-09 00:01:50,672 - language_tool_python.download_lt - INFO - Unzipping C:\Users\Dargaard\AppData\Local\Temp\tmpzzukrn7u.zip to C:\Users\Dargaard\.cache\language_tool_python.
2021-11-09 00:01:53,977 - language_tool_python.download_lt - INFO - Downloaded https://www.languagetool.org/download/LanguageTool-5.2.zip to C:\Users\Dargaard\.cache\language_tool_python.
2021-11-09 00:01:55,043 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "language_tool_python\language_tag.py", line 30, in _normalize
KeyError: 'english_canada'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "language_tool_python\language_tag.py", line 33, in _normalize
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manuskript", line 13, in <module>
  File "manuskript\main.py", line 291, in run
  File "manuskript\main.py", line 172, in prepare
  File "manuskript\mainWindow.py", line 76, in __init__
  File "manuskript\mainWindow.py", line 1403, in setupMoreUi
  File "manuskript\mainWindow.py", line 1434, in updateMenuDict
  File "manuskript\functions\spellchecker.py", line 81, in availableDictionaries
  File "manuskript\functions\spellchecker.py", line 584, in availableDictionaries
  File "manuskript\functions\spellchecker.py", line 555, in getTool
  File "language_tool_python\server.py", line 54, in __init__
  File "language_tool_python\language_tag.py", line 13, in __init__
  File "language_tool_python\language_tag.py", line 35, in _normalize
ValueError: unsupported language: 'English_Canada'

2021-11-22 17:38:20,694 - manuskript.logging - INFO - Logging to file: C:/Users/Dargaard/AppData/Local/manuskript/manuskript\logs\2021-11-22_17-38-20_manuskript#11732.log
2021-11-22 17:38:20,695 - manuskript - INFO - Operating System: Windows-10-10.0.19041-SP0
2021-11-22 17:38:20,695 - manuskript - INFO - Hardware: AMD64 / Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
2021-11-22 17:38:20,696 - manuskript - INFO - Running in a frozen (packaged) state.
2021-11-22 17:38:20,696 - manuskript - DEBUG - * sys.frozen = True
2021-11-22 17:38:20,696 - manuskript - DEBUG - * sys._MEIPASS = C:\ProgramData\chocolatey\lib\manuskript\tools\manuskript
2021-11-22 17:38:20,696 - manuskript - DEBUG - * sys.executable = 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\manuskript.exe'
2021-11-22 17:38:20,697 - manuskript - DEBUG - * sys.argv = ['C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\manuskript.exe']
2021-11-22 17:38:20,697 - manuskript - DEBUG - * sys.path = ['C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\base_library.zip',
 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\..',
 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript\\lib-dynload',
 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript']
2021-11-22 17:38:20,697 - manuskript - DEBUG - * sys.prefix = 'C:\\ProgramData\\chocolatey\\lib\\manuskript\\tools\\manuskript'
2021-11-22 17:38:20,697 - manuskript - INFO - Manuskript 0.12.0 (Python 3.8.9)
2021-11-22 17:38:20,698 - manuskript - INFO - * PyQt 5.15.4 (compiled against Qt 5.15.2)
2021-11-22 17:38:20,698 - manuskript - INFO -   * Qt 5.15.2 (runtime)
2021-11-22 17:38:20,705 - manuskript - INFO - * lxml.etree 4.6.3.0
2021-11-22 17:38:20,705 - manuskript - INFO -   * libxml   2.9.5 (compiled: 2.9.5)
2021-11-22 17:38:20,705 - manuskript - INFO -   * libxslt  1.1.30 (compiled: 1.1.30)
2021-11-22 17:38:20,705 - manuskript - INFO - * pyEnchant 3.2.0 (libenchant: 2.2.7)
2021-11-22 17:38:20,705 - manuskript - INFO - * pySpellChecker 0.6.2
2021-11-22 17:38:20,705 - manuskript - INFO - * Symspellpy 6.7.0
2021-11-22 17:38:20,730 - manuskript - INFO - * Markdown 3.3.4
2021-11-22 17:38:20,730 - manuskript - INFO - Web rendering engine: QTextEdit
2021-11-22 17:38:20,754 - manuskript.main - INFO - Preferred translation: ['en-US'] (based on available ui languages)
2021-11-22 17:38:20,754 - manuskript.main - INFO - Using the builtin translation. (U.S. English)
2021-11-22 17:38:23,051 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "language_tool_python\language_tag.py", line 30, in _normalize
KeyError: 'english_canada'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "language_tool_python\language_tag.py", line 33, in _normalize
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manuskript", line 13, in <module>
  File "manuskript\main.py", line 291, in run
  File "manuskript\main.py", line 172, in prepare
  File "manuskript\mainWindow.py", line 76, in __init__
  File "manuskript\mainWindow.py", line 1403, in setupMoreUi
  File "manuskript\mainWindow.py", line 1434, in updateMenuDict
  File "manuskript\functions\spellchecker.py", line 81, in availableDictionaries
  File "manuskript\functions\spellchecker.py", line 584, in availableDictionaries
  File "manuskript\functions\spellchecker.py", line 555, in getTool
  File "language_tool_python\server.py", line 54, in __init__
  File "language_tool_python\language_tag.py", line 13, in __init__
  File "language_tool_python\language_tag.py", line 35, in _normalize
ValueError: unsupported language: 'English_Canada'

**Comment by TheJackiMonster** [comment]
It should work fine without language_tool_python. But the next version should also handle this issue properly without crashing.
See issue #870.
