### ISSUE TITLE
Crash when adding key/value information to a character

### ISSUE THREAD

**Issue by DavidSMills** [olivierkes/manuskript#968]
Log with stacktrace:
```
2021-11-26 14:12:51,999 - manuskript.mainWindow - INFO - Project /home/david/Nextcloud/mystery_novel.msk loaded.
2021-11-26 14:15:43,986 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/models/characterPOVModel.py", line 17, in filterAcceptsRow
    return self.sourceModel().pov(sourceRow)
  File "/usr/share/manuskript/manuskript/models/characterModel.py", line 139, in pov
    return self.character(row).pov()
  File "/usr/share/manuskript/manuskript/models/characterModel.py", line 124, in character
    return self.characters[row]
IndexError: list index out of range
```

Steps to reproduce:

Case 1: 

 * Open a new project
 * Create a character
 * Add two key/value pairs

Case 2: 

 * Open a new project
 * Create two characters
 * Add three key/value pairs to the first character

**Comment by TheJackiMonster** [comment]
This has already been solved on the develop branch. The next version will fix it.
Original issue as #843.

**Comment by DavidSMills** [comment]
Thanks
