### ISSUE TITLE
Regex search causes crash

### ISSUE THREAD

**Issue by bnichs** [olivierkes/manuskript#989]
When I try and search for something with "regex' checked, it will crash the whole program if there is any issue with the pattern. For instance, searching for `^[a-Z]` yields the following crash:

```Traceback (most recent call last):
  File "/home/ben/workplace/manuskript/bin/../manuskript/ui/search.py", line 94, in search
    searchRegex = self.prepareRegex(searchText)
  File "/home/ben/workplace/manuskript/bin/../manuskript/ui/search.py", line 86, in prepareRegex
    return re.compile(searchText, flags)
  File "/usr/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range a-Z at position 2
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/home/ben/workplace/manuskript/bin/../manuskript/ui/search.py", line 94, in search
    searchRegex = self.prepareRegex(searchText)
  File "/home/ben/workplace/manuskript/bin/../manuskript/ui/search.py", line 86, in prepareRegex
    return re.compile(searchText, flags)
  File "/usr/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range a-Z at position 2```

**Comment by jdanielp** [comment]
It looks like there is no one set assigned to this issue.  If no one else is working this I can supply a quick fix by wrapping the compile in a try.  If you want a more elegant fix, let me know and I can do that also.
